<script setup lang="ts">
import { computed } from 'vue'
import Button from 'primevue/button'
import Card from 'primevue/card'
import Tag from 'primevue/tag'
import MetricCard from '@/components/MetricCard.vue'
import ModuleTabs from '@/components/ModuleTabs.vue'
import PageHeader from '@/components/PageHeader.vue'
import EmptyState from '@/components/EmptyState.vue'
import { useAppStore } from '@/stores/app'
import { formatDate, todayKey } from '@/utils/date'
import { homeTabs } from './navigation'

const store=useAppStore()
const activeLists=computed(()=>store.data.shoppingLists.filter(x=>x.status==='active'));const pendingItems=computed(()=>store.data.shoppingItems.filter(x=>!x.checked&&activeLists.value.some(list=>list.id===x.listId)));const expiring=computed(()=>store.data.inventoryItems.filter(x=>x.expiresAt&&x.expiresAt>=todayKey()).sort((a,b)=>a.expiresAt.localeCompare(b.expiresAt)).slice(0,5));const maintenance=computed(()=>[...store.data.maintenanceItems].filter(x=>x.nextService).sort((a,b)=>a.nextService.localeCompare(b.nextService)).slice(0,5));const chores=computed(()=>store.data.homeTasks.filter(x=>!x.completed).sort((a,b)=>a.nextDueDate.localeCompare(b.nextDueDate)).slice(0,5));const warranties=computed(()=>store.data.warranties.filter(x=>x.expiresAt>=todayKey()).sort((a,b)=>a.expiresAt.localeCompare(b.expiresAt)).slice(0,3))
</script>

<template><section class="page-container"><PageHeader eyebrow="Casa y compras" title="Hogar" description="Controlá lo que falta, lo que vence y lo que necesita mantenimiento."><RouterLink to="/hogar/compras"><Button label="Nueva lista" icon="pi pi-plus"/></RouterLink></PageHeader><ModuleTabs :tabs="homeTabs"/>
<div class="metrics-grid"><MetricCard label="Productos pendientes" :value="pendingItems.length" helper="en listas activas" icon="pi pi-shopping-cart" tone="violet"/><MetricCard label="Stock bajo" :value="store.lowStockItems.length" helper="productos para reponer" icon="pi pi-box" :tone="store.lowStockItems.length?'amber':'blue'"/><MetricCard label="Tareas del hogar" :value="chores.length" helper="pendientes próximas" icon="pi pi-list-check" tone="green"/><MetricCard label="Mantenimientos" :value="maintenance.length" helper="programados" icon="pi pi-wrench" tone="rose"/></div>
<div class="home-hero"><div><span class="eyebrow">Panel del hogar</span><h2>{{store.lowStockItems.length||chores.length?'Hay algunas cosas para resolver':'Todo está al día'}}</h2><p>Usá las listas y vencimientos para reducir olvidos y compras duplicadas.</p></div><div class="home-quick-links"><RouterLink to="/hogar/compras"><i class="pi pi-shopping-cart"/><span>Compras</span><b>{{pendingItems.length}}</b></RouterLink><RouterLink to="/hogar/inventario"><i class="pi pi-box"/><span>Inventario</span><b>{{store.data.inventoryItems.length}}</b></RouterLink><RouterLink to="/hogar/mantenimiento"><i class="pi pi-wrench"/><span>Mantenimiento</span><b>{{maintenance.length}}</b></RouterLink></div></div>
<div class="two-columns"><Card class="content-card"><template #title><div class="card-title"><span>Próximas tareas</span><RouterLink to="/hogar/mantenimiento">Administrar</RouterLink></div></template><template #content><div v-if="chores.length" class="smart-list"><article v-for="item in chores" :key="item.id" class="smart-row"><span class="row-icon green"><i class="pi pi-list-check"/></span><div><strong>{{item.title}}</strong><small>{{item.room}} · {{formatDate(item.nextDueDate,'dd MMM')}}</small></div><Tag :value="item.assignedTo||'Sin asignar'" severity="secondary" rounded/></article></div><EmptyState v-else icon="pi pi-list-check" title="Sin tareas pendientes" description="Las tareas domésticas próximas aparecerán acá."/></template></Card>
<Card class="content-card"><template #title><div class="card-title"><span>Vencimientos de alimentos</span><RouterLink to="/hogar/inventario">Ver inventario</RouterLink></div></template><template #content><div v-if="expiring.length" class="smart-list"><article v-for="item in expiring" :key="item.id" class="smart-row"><span class="row-icon amber"><i class="pi pi-clock"/></span><div><strong>{{item.name}}</strong><small>{{item.location}} · vence {{formatDate(item.expiresAt,'dd MMM')}}</small></div><b>{{item.quantity}} {{item.unit}}</b></article></div><EmptyState v-else icon="pi pi-clock" title="Sin vencimientos cercanos" description="Agregá fechas al inventario para evitar desperdicios."/></template></Card></div>
<div class="two-columns"><Card class="content-card"><template #title><div class="card-title"><span>Próximos servicios</span><RouterLink to="/hogar/mantenimiento">Ver todos</RouterLink></div></template><template #content><div v-if="maintenance.length" class="smart-list"><article v-for="item in maintenance" :key="item.id" class="smart-row"><span :class="['row-icon',item.status==='overdue'?'rose':item.status==='dueSoon'?'amber':'blue']"><i class="pi pi-wrench"/></span><div><strong>{{item.title}}</strong><small>{{item.asset}} · {{formatDate(item.nextService,'dd MMM yyyy')}}</small></div><Tag :value="item.status==='overdue'?'Vencido':item.status==='dueSoon'?'Próximo':'Al día'" :severity="item.status==='overdue'?'danger':item.status==='dueSoon'?'warn':'success'"/></article></div><EmptyState v-else icon="pi pi-wrench" title="Sin mantenimientos" description="Programá services y revisiones periódicas."/></template></Card>
<Card class="content-card"><template #title><div class="card-title"><span>Garantías vigentes</span><RouterLink to="/hogar/mantenimiento">Administrar</RouterLink></div></template><template #content><div v-if="warranties.length" class="smart-list"><article v-for="item in warranties" :key="item.id" class="smart-row"><span class="row-icon violet"><i class="pi pi-shield"/></span><div><strong>{{item.item}}</strong><small>{{item.store}} · hasta {{formatDate(item.expiresAt,'dd MMM yyyy')}}</small></div></article></div><EmptyState v-else icon="pi pi-shield" title="Sin garantías" description="Guardá fechas de compra y vencimiento de tus productos."/></template></Card></div>
</section></template>
