<script setup lang="ts">
import { computed, reactive, ref } from 'vue'
import Button from 'primevue/button'
import Card from 'primevue/card'
import Dialog from 'primevue/dialog'
import InputNumber from 'primevue/inputnumber'
import InputText from 'primevue/inputtext'
import Select from 'primevue/select'
import Textarea from 'primevue/textarea'
import Tag from 'primevue/tag'
import { useConfirm } from 'primevue/useconfirm'
import { useToast } from 'primevue/usetoast'
import EmptyState from '@/components/EmptyState.vue'
import ModuleTabs from '@/components/ModuleTabs.vue'
import PageHeader from '@/components/PageHeader.vue'
import { useAppStore } from '@/stores/app'
import type { InventoryItem } from '@/types/domain'
import { formatDate, todayKey } from '@/utils/date'
import { createId } from '@/utils/id'
import { homeTabs } from './navigation'

const store=useAppStore();const toast=useToast();const confirm=useConfirm();const visible=ref(false);const editingId=ref<string|null>(null);const search=ref('');const categoryFilter=ref('Todas');const stockFilter=ref<'all'|'low'|'expiring'>('all')
const categories=['Alimentos','Bebidas','Limpieza','Higiene','Farmacia','Herramientas','Mascotas','Otros'];const locations=['Alacena','Heladera','Freezer','Baño','Lavadero','Placard','Depósito','Otro'];const units=['unidad','kg','g','litro','ml','paquete','caja','rollo']
const form=reactive({name:'',quantity:1,unit:'unidad',category:categories[0],location:locations[0],minStock:1,expiresAt:'',notes:''})
const filtered=computed(()=>[...store.data.inventoryItems].filter(x=>categoryFilter.value==='Todas'||x.category===categoryFilter.value).filter(x=>stockFilter.value==='all'||stockFilter.value==='low'&&x.quantity<=x.minStock||stockFilter.value==='expiring'&&x.expiresAt&&x.expiresAt<=new Date(Date.now()+14*86400000).toISOString().slice(0,10)).filter(x=>`${x.name} ${x.location} ${x.notes}`.toLowerCase().includes(search.value.toLowerCase())).sort((a,b)=>Number(a.quantity<=a.minStock)-Number(b.quantity<=b.minStock)||a.name.localeCompare(b.name)))
const expiringCount=computed(()=>store.data.inventoryItems.filter(x=>x.expiresAt&&x.expiresAt>=todayKey()&&x.expiresAt<=new Date(Date.now()+14*86400000).toISOString().slice(0,10)).length)
function open(item?:InventoryItem){editingId.value=item?.id??null;Object.assign(form,item??{name:'',quantity:1,unit:'unidad',category:categories[0],location:locations[0],minStock:1,expiresAt:'',notes:''});visible.value=true}
function save(){if(!form.name.trim()){toast.add({severity:'warn',summary:'Producto sin nombre',detail:'Indicá qué querés guardar.',life:2400});return}store.upsert('inventoryItems',{id:editingId.value??createId('inventory'),...form,name:form.name.trim()});visible.value=false}
function remove(item:InventoryItem){confirm.require({message:`¿Eliminar “${item.name}” del inventario?`,header:'Eliminar producto',icon:'pi pi-exclamation-triangle',rejectProps:{label:'Cancelar',severity:'secondary',outlined:true},acceptProps:{label:'Eliminar',severity:'danger'},accept:()=>store.remove('inventoryItems',item.id)})}
function adjust(item:InventoryItem,delta:number){store.upsert('inventoryItems',{...item,quantity:Math.max(0,Number((item.quantity+delta).toFixed(2)))})}
function addLowStockToShopping(){let list=store.data.shoppingLists.find(x=>x.status==='active');if(!list){list={id:createId('shopping-list'),title:'Reposición del hogar',store:'',budget:0,status:'active',createdAt:new Date().toISOString()};store.upsert('shoppingLists',list)}let added=0;store.lowStockItems.forEach(item=>{if(!store.data.shoppingItems.some(x=>x.listId===list!.id&&x.name.toLowerCase()===item.name.toLowerCase())){store.upsert('shoppingItems',{id:createId('shopping-item'),listId:list!.id,name:item.name,quantity:Math.max(1,item.minStock-item.quantity+1),unit:item.unit,category:item.category,estimatedPrice:0,actualPrice:0,checked:false,frequent:true});added++}});toast.add({severity:'success',summary:'Lista actualizada',detail:`Se agregaron ${added} productos para reponer.`,life:2600})}
</script>

<template><section class="page-container"><PageHeader eyebrow="Stock y vencimientos" title="Inventario del hogar" description="Sabé qué tenés, dónde está, cuándo vence y qué conviene reponer."><div class="header-actions"><Button v-if="store.lowStockItems.length" label="Enviar faltantes a compras" icon="pi pi-shopping-cart" severity="secondary" outlined @click="addLowStockToShopping"/><Button label="Agregar producto" icon="pi pi-plus" @click="open()"/></div></PageHeader><ModuleTabs :tabs="homeTabs"/>
<div class="metrics-grid"><article class="mini-stat"><span class="row-icon violet"><i class="pi pi-box"/></span><div><strong>{{store.data.inventoryItems.length}}</strong><small>productos registrados</small></div></article><article class="mini-stat"><span class="row-icon amber"><i class="pi pi-exclamation-triangle"/></span><div><strong>{{store.lowStockItems.length}}</strong><small>con stock bajo</small></div></article><article class="mini-stat"><span class="row-icon rose"><i class="pi pi-clock"/></span><div><strong>{{expiringCount}}</strong><small>vencen en 14 días</small></div></article></div>
<div class="filter-bar"><span class="search-box"><i class="pi pi-search"/><InputText v-model="search" placeholder="Buscar producto o ubicación..."/></span><Select v-model="categoryFilter" :options="['Todas',...categories]"/><Select v-model="stockFilter" :options="[{label:'Todo el inventario',value:'all'},{label:'Stock bajo',value:'low'},{label:'Próximos a vencer',value:'expiring'}]" option-label="label" option-value="value"/></div>
<div v-if="filtered.length" class="inventory-grid"><Card v-for="item in filtered" :key="item.id" :class="['inventory-card',{low:item.quantity<=item.minStock,expiring:item.expiresAt&&item.expiresAt<=new Date(Date.now()+14*86400000).toISOString().slice(0,10)}]"><template #content><div class="inventory-head"><span class="row-icon blue"><i class="pi pi-box"/></span><div><h3>{{item.name}}</h3><p>{{item.category}} · {{item.location}}</p></div><Tag v-if="item.quantity<=item.minStock" value="Reponer" severity="warn" rounded/><Tag v-else value="Disponible" severity="success" rounded/></div><div class="stock-counter"><Button icon="pi pi-minus" rounded text :disabled="item.quantity<=0" @click="adjust(item,-1)"/><strong>{{item.quantity}} <small>{{item.unit}}</small></strong><Button icon="pi pi-plus" rounded text @click="adjust(item,1)"/></div><div class="entity-meta"><span><i class="pi pi-bell"/> Mínimo: {{item.minStock}} {{item.unit}}</span><span v-if="item.expiresAt"><i class="pi pi-clock"/> Vence {{formatDate(item.expiresAt,'dd/MM/yyyy')}}</span></div><p v-if="item.notes" class="note">{{item.notes}}</p><div class="entity-actions"><Button label="Editar" icon="pi pi-pencil" text @click="open(item)"/><Button label="Eliminar" icon="pi pi-trash" text severity="danger" @click="remove(item)"/></div></template></Card></div><EmptyState v-else icon="pi pi-box" title="No hay productos para mostrar" description="Agregá elementos al inventario o modificá los filtros."><Button label="Agregar producto" icon="pi pi-plus" @click="open()"/></EmptyState>
<Dialog v-model:visible="visible" modal :header="editingId?'Editar producto':'Nuevo producto de inventario'" :style="{width:'min(94vw,42rem)'}"><div class="form-grid"><label class="field full"><span>Producto</span><InputText v-model="form.name" autofocus/></label><label class="field"><span>Cantidad</span><InputNumber v-model="form.quantity" :min="0" :max-fraction-digits="2"/></label><label class="field"><span>Unidad</span><Select v-model="form.unit" :options="units" editable/></label><label class="field"><span>Categoría</span><Select v-model="form.category" :options="categories" editable/></label><label class="field"><span>Ubicación</span><Select v-model="form.location" :options="locations" editable/></label><label class="field"><span>Stock mínimo</span><InputNumber v-model="form.minStock" :min="0" :max-fraction-digits="2"/></label><label class="field"><span>Fecha de vencimiento</span><InputText v-model="form.expiresAt" type="date"/></label><label class="field full"><span>Notas</span><Textarea v-model="form.notes" rows="3"/></label></div><template #footer><Button label="Cancelar" text @click="visible=false"/><Button label="Guardar" icon="pi pi-check" @click="save"/></template></Dialog>
</section></template>
