<script setup lang="ts">
import { computed, reactive, ref } from 'vue'
import Button from 'primevue/button'
import Card from 'primevue/card'
import Dialog from 'primevue/dialog'
import InputNumber from 'primevue/inputnumber'
import InputText from 'primevue/inputtext'
import Select from 'primevue/select'
import Textarea from 'primevue/textarea'
import Tag from 'primevue/tag'
import { useConfirm } from 'primevue/useconfirm'
import { useToast } from 'primevue/usetoast'
import EmptyState from '@/components/EmptyState.vue'
import ModuleTabs from '@/components/ModuleTabs.vue'
import PageHeader from '@/components/PageHeader.vue'
import { useAppStore } from '@/stores/app'
import type { HomeTask, MaintenanceItem, Warranty } from '@/types/domain'
import { formatCurrency, formatDate, todayKey } from '@/utils/date'
import { createId } from '@/utils/id'
import { homeTabs } from './navigation'

const store=useAppStore();const toast=useToast();const confirm=useConfirm();const section=ref<'tasks'|'maintenance'|'warranties'>('tasks');const taskVisible=ref(false);const maintenanceVisible=ref(false);const warrantyVisible=ref(false);const editingId=ref<string|null>(null)
const rooms=['Cocina','Baño','Dormitorio','Living','Lavadero','Balcón','Patio','General'];const categories=['Electrodomésticos','Climatización','Computación','Plomería','Electricidad','Muebles','Vehículo','Otro']
const taskForm=reactive({title:'',room:'General',frequency:'weekly' as 'once'|'weekly'|'monthly',nextDueDate:todayKey(),assignedTo:'',completed:false});const maintenanceForm=reactive({title:'',asset:'',category:categories[0],lastService:'',nextService:todayKey(),cost:0,provider:'',notes:'',status:'ok' as 'ok'|'dueSoon'|'overdue'});const warrantyForm=reactive({item:'',purchaseDate:todayKey(),expiresAt:'',store:'',serial:'',notes:''})
const tasks=computed(()=>[...store.data.homeTasks].sort((a,b)=>Number(a.completed)-Number(b.completed)||a.nextDueDate.localeCompare(b.nextDueDate)));const maintenances=computed(()=>[...store.data.maintenanceItems].sort((a,b)=>a.nextService.localeCompare(b.nextService)));const warranties=computed(()=>[...store.data.warranties].sort((a,b)=>a.expiresAt.localeCompare(b.expiresAt)))
function openTask(item?:HomeTask){editingId.value=item?.id??null;Object.assign(taskForm,item??{title:'',room:'General',frequency:'weekly',nextDueDate:todayKey(),assignedTo:'',completed:false});taskVisible.value=true}
function saveTask(){if(!taskForm.title.trim()){toast.add({severity:'warn',summary:'Tarea sin nombre',detail:'Indicá qué hay que hacer.',life:2300});return}store.upsert('homeTasks',{id:editingId.value??createId('home-task'),...taskForm,title:taskForm.title.trim()});taskVisible.value=false}
function completeTask(item:HomeTask){store.upsert('homeTasks',{...item,completed:!item.completed})}
function openMaintenance(item?:MaintenanceItem){editingId.value=item?.id??null;Object.assign(maintenanceForm,item??{title:'',asset:'',category:categories[0],lastService:'',nextService:todayKey(),cost:0,provider:'',notes:'',status:'ok'});maintenanceVisible.value=true}
function saveMaintenance(){if(!maintenanceForm.title.trim()||!maintenanceForm.asset.trim()){toast.add({severity:'warn',summary:'Mantenimiento incompleto',detail:'Indicá tarea y equipo o elemento.',life:2500});return}const today=todayKey();const soon=new Date(Date.now()+30*86400000).toISOString().slice(0,10);maintenanceForm.status=maintenanceForm.nextService<today?'overdue':maintenanceForm.nextService<=soon?'dueSoon':'ok';store.upsert('maintenanceItems',{id:editingId.value??createId('maintenance'),...maintenanceForm,title:maintenanceForm.title.trim(),asset:maintenanceForm.asset.trim()});maintenanceVisible.value=false}
function openWarranty(item?:Warranty){editingId.value=item?.id??null;Object.assign(warrantyForm,item??{item:'',purchaseDate:todayKey(),expiresAt:'',store:'',serial:'',notes:''});warrantyVisible.value=true}
function saveWarranty(){if(!warrantyForm.item.trim()||!warrantyForm.purchaseDate){toast.add({severity:'warn',summary:'Garantía incompleta',detail:'Indicá producto y fecha de compra.',life:2400});return}store.upsert('warranties',{id:editingId.value??createId('warranty'),...warrantyForm,item:warrantyForm.item.trim()});warrantyVisible.value=false}
function remove(collection:'homeTasks'|'maintenanceItems'|'warranties',id:string,title:string){confirm.require({message:`¿Eliminar “${title}”?`,header:'Confirmar eliminación',icon:'pi pi-exclamation-triangle',rejectProps:{label:'Cancelar',severity:'secondary',outlined:true},acceptProps:{label:'Eliminar',severity:'danger'},accept:()=>store.remove(collection,id)})}
</script>

<template><section class="page-container"><PageHeader eyebrow="Cuidado de la casa" title="Mantenimiento" description="Programá tareas domésticas, services y garantías para evitar olvidos costosos."><Button :label="section==='tasks'?'Nueva tarea':section==='maintenance'?'Nuevo mantenimiento':'Nueva garantía'" icon="pi pi-plus" @click="section==='tasks'?openTask():section==='maintenance'?openMaintenance():openWarranty()"/></PageHeader><ModuleTabs :tabs="homeTabs"/>
<div class="segment-control"><button :class="{active:section==='tasks'}" @click="section='tasks'"><i class="pi pi-list-check"/> Tareas del hogar <b>{{store.data.homeTasks.filter(x=>!x.completed).length}}</b></button><button :class="{active:section==='maintenance'}" @click="section='maintenance'"><i class="pi pi-wrench"/> Services <b>{{store.data.maintenanceItems.length}}</b></button><button :class="{active:section==='warranties'}" @click="section='warranties'"><i class="pi pi-shield"/> Garantías <b>{{store.data.warranties.length}}</b></button></div>
<div v-if="section==='tasks'"><div v-if="tasks.length" class="task-list home-task-list"><Card v-for="item in tasks" :key="item.id" :class="['task-card',{done:item.completed}]"><template #content><button class="task-check" @click="completeTask(item)"><i :class="item.completed?'pi pi-check-circle':'pi pi-circle'"/></button><div class="task-content"><div class="task-title-row"><h3>{{item.title}}</h3><Tag :value="item.frequency==='once'?'Una vez':item.frequency==='weekly'?'Semanal':'Mensual'" severity="secondary"/></div><div class="task-meta"><span><i class="pi pi-home"/> {{item.room}}</span><span><i class="pi pi-calendar"/> {{formatDate(item.nextDueDate,'dd MMM yyyy')}}</span><span v-if="item.assignedTo"><i class="pi pi-user"/> {{item.assignedTo}}</span></div></div><div class="task-menu"><Button icon="pi pi-pencil" text rounded @click="openTask(item)"/><Button icon="pi pi-trash" text rounded severity="danger" @click="remove('homeTasks',item.id,item.title)"/></div></template></Card></div><EmptyState v-else icon="pi pi-list-check" title="Sin tareas domésticas" description="Agregá limpiezas y tareas repetitivas por ambiente."/></div>
<div v-else-if="section==='maintenance'"><div v-if="maintenances.length" class="maintenance-timeline"><Card v-for="item in maintenances" :key="item.id" :class="['maintenance-card',item.status]"><template #content><span :class="['maintenance-marker',item.status]"><i class="pi pi-wrench"/></span><div class="maintenance-content"><div class="entity-header"><div><h3>{{item.title}}</h3><p>{{item.asset}} · {{item.category}}</p></div><Tag :value="item.status==='overdue'?'Vencido':item.status==='dueSoon'?'Próximo':'Al día'" :severity="item.status==='overdue'?'danger':item.status==='dueSoon'?'warn':'success'"/></div><div class="maintenance-details"><span><small>Próximo service</small><strong>{{formatDate(item.nextService,'dd MMM yyyy')}}</strong></span><span v-if="item.lastService"><small>Último service</small><strong>{{formatDate(item.lastService,'dd MMM yyyy')}}</strong></span><span><small>Costo estimado</small><strong>{{formatCurrency(item.cost,store.data.settings.currency)}}</strong></span><span v-if="item.provider"><small>Proveedor</small><strong>{{item.provider}}</strong></span></div><p v-if="item.notes" class="note">{{item.notes}}</p><div class="entity-actions"><Button label="Editar" icon="pi pi-pencil" text @click="openMaintenance(item)"/><Button label="Eliminar" icon="pi pi-trash" text severity="danger" @click="remove('maintenanceItems',item.id,item.title)"/></div></div></template></Card></div><EmptyState v-else icon="pi pi-wrench" title="Sin mantenimientos programados" description="Agendá revisiones de equipos, instalaciones y electrodomésticos."/></div>
<div v-else><div v-if="warranties.length" class="warranty-grid"><Card v-for="item in warranties" :key="item.id" class="warranty-card"><template #content><span class="document-icon"><i class="pi pi-shield"/></span><Tag :value="item.expiresAt&&item.expiresAt<store.today?'Vencida':'Vigente'" :severity="item.expiresAt&&item.expiresAt<store.today?'danger':'success'" rounded/><h3>{{item.item}}</h3><p>Comprado {{formatDate(item.purchaseDate,'dd MMM yyyy')}}</p><div class="entity-meta"><span v-if="item.expiresAt"><i class="pi pi-calendar"/> Garantía hasta {{formatDate(item.expiresAt,'dd MMM yyyy')}}</span><span v-if="item.store"><i class="pi pi-building"/> {{item.store}}</span><span v-if="item.serial"><i class="pi pi-barcode"/> {{item.serial}}</span></div><p v-if="item.notes" class="note">{{item.notes}}</p><div class="entity-actions"><Button label="Editar" icon="pi pi-pencil" text @click="openWarranty(item)"/><Button icon="pi pi-trash" text severity="danger" @click="remove('warranties',item.id,item.item)"/></div></template></Card></div><EmptyState v-else icon="pi pi-shield" title="Sin garantías registradas" description="Guardá productos, comprobantes y fechas de vencimiento."/></div>
<Dialog v-model:visible="taskVisible" modal :header="editingId?'Editar tarea':'Nueva tarea del hogar'" :style="{width:'min(92vw,36rem)'}"><div class="form-grid"><label class="field full"><span>Tarea</span><InputText v-model="taskForm.title" autofocus/></label><label class="field"><span>Ambiente</span><Select v-model="taskForm.room" :options="rooms" editable/></label><label class="field"><span>Frecuencia</span><Select v-model="taskForm.frequency" :options="[{label:'Una vez',value:'once'},{label:'Semanal',value:'weekly'},{label:'Mensual',value:'monthly'}]" option-label="label" option-value="value"/></label><label class="field"><span>Próxima fecha</span><InputText v-model="taskForm.nextDueDate" type="date"/></label><label class="field"><span>Asignada a</span><InputText v-model="taskForm.assignedTo"/></label></div><template #footer><Button label="Cancelar" text @click="taskVisible=false"/><Button label="Guardar" icon="pi pi-check" @click="saveTask"/></template></Dialog>
<Dialog v-model:visible="maintenanceVisible" modal :header="editingId?'Editar mantenimiento':'Nuevo mantenimiento'" :style="{width:'min(94vw,44rem)'}"><div class="form-grid"><label class="field"><span>Tarea</span><InputText v-model="maintenanceForm.title" placeholder="Ej. Limpieza de filtros" autofocus/></label><label class="field"><span>Equipo o elemento</span><InputText v-model="maintenanceForm.asset" placeholder="Ej. Aire acondicionado"/></label><label class="field"><span>Categoría</span><Select v-model="maintenanceForm.category" :options="categories" editable/></label><label class="field"><span>Proveedor</span><InputText v-model="maintenanceForm.provider"/></label><label class="field"><span>Último service</span><InputText v-model="maintenanceForm.lastService" type="date"/></label><label class="field"><span>Próximo service</span><InputText v-model="maintenanceForm.nextService" type="date"/></label><label class="field"><span>Costo estimado</span><InputNumber v-model="maintenanceForm.cost" mode="currency" :currency="store.data.settings.currency" locale="es-AR"/></label><label class="field full"><span>Notas</span><Textarea v-model="maintenanceForm.notes" rows="3"/></label></div><template #footer><Button label="Cancelar" text @click="maintenanceVisible=false"/><Button label="Guardar" icon="pi pi-check" @click="saveMaintenance"/></template></Dialog>
<Dialog v-model:visible="warrantyVisible" modal :header="editingId?'Editar garantía':'Nueva garantía'" :style="{width:'min(92vw,38rem)'}"><div class="form-grid"><label class="field full"><span>Producto</span><InputText v-model="warrantyForm.item" autofocus/></label><label class="field"><span>Fecha de compra</span><InputText v-model="warrantyForm.purchaseDate" type="date"/></label><label class="field"><span>Vencimiento de garantía</span><InputText v-model="warrantyForm.expiresAt" type="date"/></label><label class="field"><span>Comercio</span><InputText v-model="warrantyForm.store"/></label><label class="field"><span>Número de serie</span><InputText v-model="warrantyForm.serial"/></label><label class="field full"><span>Notas</span><Textarea v-model="warrantyForm.notes" rows="3"/></label></div><template #footer><Button label="Cancelar" text @click="warrantyVisible=false"/><Button label="Guardar" icon="pi pi-check" @click="saveWarranty"/></template></Dialog>
</section></template>
