<script setup lang="ts">
import { computed, reactive, ref, watch } from 'vue'
import Button from 'primevue/button'
import Card from 'primevue/card'
import Checkbox from 'primevue/checkbox'
import Dialog from 'primevue/dialog'
import InputNumber from 'primevue/inputnumber'
import InputText from 'primevue/inputtext'
import Select from 'primevue/select'
import Tag from 'primevue/tag'
import ToggleSwitch from 'primevue/toggleswitch'
import { useConfirm } from 'primevue/useconfirm'
import { useToast } from 'primevue/usetoast'
import EmptyState from '@/components/EmptyState.vue'
import ModuleTabs from '@/components/ModuleTabs.vue'
import PageHeader from '@/components/PageHeader.vue'
import { useAppStore } from '@/stores/app'
import type { ShoppingItem, ShoppingList } from '@/types/domain'
import { formatCurrency, todayKey } from '@/utils/date'
import { createId } from '@/utils/id'
import { homeTabs } from './navigation'

const store=useAppStore();const toast=useToast();const confirm=useConfirm();const listVisible=ref(false);const itemVisible=ref(false);const editingId=ref<string|null>(null);const selectedListId=ref(store.data.shoppingLists.find(x=>x.status==='active')?.id??'');const quickItem=ref('')
const categories=['Frutas y verduras','Carnes','Lácteos','Almacén','Limpieza','Higiene','Bebidas','Mascotas','Otros'];const units=['unidad','kg','g','litro','ml','paquete','caja','docena']
const listForm=reactive({title:'Compra semanal',store:'',budget:0,status:'active' as 'active'|'completed'});const itemForm=reactive({name:'',quantity:1,unit:'unidad',category:categories[0],estimatedPrice:0,actualPrice:0,checked:false,frequent:false})
const activeLists=computed(()=>store.data.shoppingLists.filter(x=>x.status==='active'));const selectedList=computed(()=>store.data.shoppingLists.find(x=>x.id===selectedListId.value));const items=computed(()=>store.data.shoppingItems.filter(x=>x.listId===selectedListId.value).sort((a,b)=>Number(a.checked)-Number(b.checked)||a.category.localeCompare(b.category)));const estimated=computed(()=>items.value.reduce((s,x)=>s+x.estimatedPrice*x.quantity,0));const actual=computed(()=>items.value.reduce((s,x)=>s+(x.actualPrice||x.estimatedPrice)*x.quantity,0));const checked=computed(()=>items.value.filter(x=>x.checked).length);const grouped=computed(()=>{const map=new Map<string,ShoppingItem[]>();items.value.forEach(item=>map.set(item.category,[...(map.get(item.category)??[]),item]));return [...map.entries()]})
watch(activeLists,(lists)=>{if(!selectedListId.value&&lists.length)selectedListId.value=lists[0].id},{immediate:true})
function openList(item?:ShoppingList){editingId.value=item?.id??null;Object.assign(listForm,item??{title:'Compra semanal',store:'',budget:0,status:'active'});listVisible.value=true}
function saveList(){if(!listForm.title.trim()){toast.add({severity:'warn',summary:'Lista sin nombre',detail:'Indicá un título para identificarla.',life:2400});return}const id=editingId.value??createId('shopping-list');store.upsert('shoppingLists',{id,...listForm,title:listForm.title.trim(),createdAt:store.data.shoppingLists.find(x=>x.id===id)?.createdAt??new Date().toISOString()});selectedListId.value=id;listVisible.value=false}
function openItem(item?:ShoppingItem){if(!selectedListId.value){openList();return}editingId.value=item?.id??null;Object.assign(itemForm,item??{name:'',quantity:1,unit:'unidad',category:categories[0],estimatedPrice:0,actualPrice:0,checked:false,frequent:false});itemVisible.value=true}
function saveItem(){if(!itemForm.name.trim()){toast.add({severity:'warn',summary:'Producto sin nombre',detail:'Indicá qué querés comprar.',life:2400});return}store.upsert('shoppingItems',{id:editingId.value??createId('shopping-item'),listId:selectedListId.value,...itemForm,name:itemForm.name.trim()});itemVisible.value=false}
function quickAdd(){if(!quickItem.value.trim()||!selectedListId.value)return;store.upsert('shoppingItems',{id:createId('shopping-item'),listId:selectedListId.value,name:quickItem.value.trim(),quantity:1,unit:'unidad',category:'Otros',estimatedPrice:0,actualPrice:0,checked:false,frequent:false});quickItem.value=''}
function toggle(item:ShoppingItem){store.upsert('shoppingItems',{...item,checked:!item.checked})}
function removeItem(item:ShoppingItem){store.remove('shoppingItems',item.id)}
function removeList(item:ShoppingList){confirm.require({message:`¿Eliminar “${item.title}” y todos sus productos?`,header:'Eliminar lista',icon:'pi pi-exclamation-triangle',rejectProps:{label:'Cancelar',severity:'secondary',outlined:true},acceptProps:{label:'Eliminar',severity:'danger'},accept:()=>{store.remove('shoppingLists',item.id);store.data.shoppingItems=store.data.shoppingItems.filter(x=>x.listId!==item.id);selectedListId.value=activeLists.value.find(x=>x.id!==item.id)?.id??''}})}
function finishList(){if(!selectedList.value)return;confirm.require({message:`Se registrará un gasto de ${formatCurrency(actual.value,store.data.settings.currency)} y la lista quedará finalizada.`,header:'Finalizar compra',icon:'pi pi-check-circle',rejectProps:{label:'Cancelar',severity:'secondary',outlined:true},acceptProps:{label:'Finalizar y registrar gasto',severity:'success'},accept:()=>{store.upsert('transactions',{id:createId('transaction'),type:'expense',title:selectedList.value!.title,amount:actual.value,category:'Alimentos',date:todayKey(),account:'Cuenta principal',paymentMethod:'Débito',notes:`Compra en ${selectedList.value!.store||'comercio no indicado'}`,tags:['compras','hogar']});store.upsert('shoppingLists',{...selectedList.value!,status:'completed'});toast.add({severity:'success',summary:'Compra finalizada',detail:'El gasto fue agregado a Finanzas.',life:3000});selectedListId.value=activeLists.value.find(x=>x.id!==selectedList.value!.id)?.id??''}})}
</script>

<template><section class="page-container"><PageHeader eyebrow="Supermercado y compras" title="Listas de compra" description="Prepará productos, cantidades y precios; al finalizar, registrá el gasto automáticamente."><Button label="Nueva lista" icon="pi pi-plus" @click="openList()"/></PageHeader><ModuleTabs :tabs="homeTabs"/>
<div v-if="activeLists.length" class="shopping-layout"><aside class="shopping-sidebar"><div class="shopping-sidebar__title"><strong>Listas activas</strong><Button icon="pi pi-plus" text rounded @click="openList()"/></div><button v-for="list in activeLists" :key="list.id" :class="{active:selectedListId===list.id}" @click="selectedListId=list.id"><span class="row-icon violet"><i class="pi pi-shopping-bag"/></span><div><strong>{{list.title}}</strong><small>{{store.data.shoppingItems.filter(x=>x.listId===list.id&&!x.checked).length}} pendientes · {{list.store||'Sin tienda'}}</small></div></button></aside>
<div v-if="selectedList" class="shopping-main"><div class="shopping-header"><div><span class="eyebrow">Lista activa</span><h2>{{selectedList.title}}</h2><p>{{selectedList.store||'Sin comercio definido'}}</p></div><div class="header-actions"><Button label="Editar lista" icon="pi pi-pencil" severity="secondary" outlined @click="openList(selectedList)"/><Button icon="pi pi-trash" severity="danger" text @click="removeList(selectedList)"/></div></div><div class="shopping-summary"><article><small>Productos</small><strong>{{checked}}/{{items.length}}</strong></article><article><small>Estimado</small><strong>{{formatCurrency(estimated,store.data.settings.currency)}}</strong></article><article><small>Total real</small><strong>{{formatCurrency(actual,store.data.settings.currency)}}</strong></article><article :class="selectedList.budget&&actual>selectedList.budget?'danger':''"><small>Presupuesto</small><strong>{{selectedList.budget?formatCurrency(selectedList.budget,store.data.settings.currency):'Sin límite'}}</strong></article></div><div class="quick-capture shopping"><span><i class="pi pi-plus"/></span><InputText v-model="quickItem" placeholder="Agregar producto rápido..." @keyup.enter="quickAdd"/><Button label="Agregar" @click="quickAdd"/><Button label="Completar detalles" icon="pi pi-sliders-h" severity="secondary" text @click="openItem()"/></div><div v-if="grouped.length" class="shopping-groups"><section v-for="[category,categoryItems] in grouped" :key="category"><h3>{{category}} <Tag :value="String(categoryItems.length)" severity="secondary" rounded/></h3><article v-for="item in categoryItems" :key="item.id" :class="{checked:item.checked}"><Checkbox :model-value="item.checked" binary @update:model-value="toggle(item)"/><div><strong>{{item.name}}</strong><small>{{item.quantity}} {{item.unit}}<template v-if="item.frequent"> · Frecuente</template></small></div><label><small>Precio real</small><InputNumber v-model="item.actualPrice" mode="currency" :currency="store.data.settings.currency" locale="es-AR" :min="0" @update:model-value="store.upsert('shoppingItems',{...item})"/></label><b>{{formatCurrency((item.actualPrice||item.estimatedPrice)*item.quantity,store.data.settings.currency)}}</b><span><Button icon="pi pi-pencil" text rounded @click="openItem(item)"/><Button icon="pi pi-trash" text rounded severity="danger" @click="removeItem(item)"/></span></article></section></div><EmptyState v-else icon="pi pi-shopping-cart" title="La lista está vacía" description="Agregá productos con el campo rápido o completá todos sus detalles."/><div v-if="items.length" class="shopping-footer"><div><strong>{{checked===items.length?'¡Compra completa!':`${items.length-checked} productos pendientes`}}</strong><small>Revisá los precios reales antes de finalizar.</small></div><Button label="Finalizar compra y registrar gasto" icon="pi pi-check" severity="success" :disabled="!items.length" @click="finishList"/></div></div></div>
<EmptyState v-else icon="pi pi-shopping-cart" title="No tenés listas activas" description="Creá una lista para el supermercado, farmacia, ferretería o cualquier compra."><Button label="Crear primera lista" icon="pi pi-plus" @click="openList()"/></EmptyState>
<Dialog v-model:visible="listVisible" modal :header="editingId?'Editar lista':'Nueva lista'" :style="{width:'min(92vw,34rem)'}"><div class="form-grid"><label class="field full"><span>Nombre</span><InputText v-model="listForm.title" autofocus/></label><label class="field"><span>Comercio</span><InputText v-model="listForm.store" placeholder="Opcional"/></label><label class="field"><span>Presupuesto</span><InputNumber v-model="listForm.budget" mode="currency" :currency="store.data.settings.currency" locale="es-AR"/></label></div><template #footer><Button label="Cancelar" text @click="listVisible=false"/><Button label="Guardar lista" icon="pi pi-check" @click="saveList"/></template></Dialog>
<Dialog v-model:visible="itemVisible" modal :header="editingId?'Editar producto':'Nuevo producto'" :style="{width:'min(92vw,40rem)'}"><div class="form-grid"><label class="field full"><span>Producto</span><InputText v-model="itemForm.name" autofocus/></label><label class="field"><span>Cantidad</span><InputNumber v-model="itemForm.quantity" :min="0.01" :min-fraction-digits="0" :max-fraction-digits="2"/></label><label class="field"><span>Unidad</span><Select v-model="itemForm.unit" :options="units" editable/></label><label class="field"><span>Categoría</span><Select v-model="itemForm.category" :options="categories" editable/></label><label class="field"><span>Precio estimado unitario</span><InputNumber v-model="itemForm.estimatedPrice" mode="currency" :currency="store.data.settings.currency" locale="es-AR"/></label><label class="field"><span>Precio real unitario</span><InputNumber v-model="itemForm.actualPrice" mode="currency" :currency="store.data.settings.currency" locale="es-AR"/></label><label class="switch-field full"><span><strong>Producto frecuente</strong><small>Podrá sugerirse en próximas listas.</small></span><ToggleSwitch v-model="itemForm.frequent"/></label></div><template #footer><Button label="Cancelar" text @click="itemVisible=false"/><Button label="Guardar producto" icon="pi pi-check" @click="saveItem"/></template></Dialog>
</section></template>
