<script setup lang="ts">
import { computed, reactive, ref } from 'vue'
import { addDays, format, isBefore, parseISO } from 'date-fns'
import Button from 'primevue/button'
import Card from 'primevue/card'
import Checkbox from 'primevue/checkbox'
import Dialog from 'primevue/dialog'
import InputNumber from 'primevue/inputnumber'
import InputText from 'primevue/inputtext'
import Select from 'primevue/select'
import Textarea from 'primevue/textarea'
import Tag from 'primevue/tag'
import { useConfirm } from 'primevue/useconfirm'
import { useToast } from 'primevue/usetoast'
import EmptyState from '@/components/EmptyState.vue'
import PageHeader from '@/components/PageHeader.vue'
import { useAppStore } from '@/stores/app'
import type { PersonalTask, Recurrence, TaskPriority, TaskStatus } from '@/types/domain'
import { formatDate, todayKey } from '@/utils/date'
import { createId } from '@/utils/id'

const store=useAppStore();const toast=useToast();const confirm=useConfirm();const visible=ref(false);const editingId=ref<string|null>(null);const view=ref<'inbox'|'today'|'week'|'all'>('today');const search=ref('');const priorityFilter=ref<'all'|TaskPriority>('all');const quickTitle=ref('');const subtaskText=ref('')
const priorities=[{label:'Baja',value:'low'},{label:'Media',value:'medium'},{label:'Alta',value:'high'},{label:'Urgente',value:'urgent'}];const statuses=[{label:'Bandeja',value:'inbox'},{label:'Pendiente',value:'todo'},{label:'En curso',value:'doing'},{label:'Completada',value:'done'}];const recurrences=[{label:'No repetir',value:'none'},{label:'Diariamente',value:'daily'},{label:'Semanalmente',value:'weekly'},{label:'Mensualmente',value:'monthly'}]
const form=reactive({title:'',description:'',status:'todo' as TaskStatus,priority:'medium' as TaskPriority,dueDate:todayKey(),dueTime:'',tagsText:'',subtasks:[] as {id:string;title:string;completed:boolean}[],recurrence:'none' as Recurrence,reminderMinutes:30,estimatedMinutes:30,project:''})
const endWeek=computed(()=>format(addDays(new Date(),7),'yyyy-MM-dd'))
const filtered=computed(()=>[...store.data.tasks].filter(item=>{if(view.value==='inbox')return item.status==='inbox';if(view.value==='today')return item.dueDate===store.today&&item.status!=='done';if(view.value==='week')return item.dueDate>=store.today&&item.dueDate<=endWeek.value&&item.status!=='done';return true}).filter(item=>priorityFilter.value==='all'||item.priority===priorityFilter.value).filter(item=>`${item.title} ${item.description} ${item.tags.join(' ')} ${item.project}`.toLowerCase().includes(search.value.toLowerCase())).sort((a,b)=>`${a.status==='done'?1:0}${a.dueDate||'9999'}${a.dueTime}`.localeCompare(`${b.status==='done'?1:0}${b.dueDate||'9999'}${b.dueTime}`)))
const todayCount=computed(()=>store.data.tasks.filter(item=>item.dueDate===store.today&&item.status!=='done').length);const inboxCount=computed(()=>store.data.tasks.filter(item=>item.status==='inbox').length);const overdueCount=computed(()=>store.data.tasks.filter(item=>item.status!=='done'&&item.dueDate&&isBefore(parseISO(item.dueDate),parseISO(store.today))).length);const completedWeek=computed(()=>store.data.tasks.filter(item=>item.status==='done'&&item.completedAt&&item.completedAt.slice(0,10)>=format(addDays(new Date(),-7),'yyyy-MM-dd')).length)
function quickAdd(){if(!quickTitle.value.trim())return;store.upsert('tasks',{id:createId('task'),title:quickTitle.value.trim(),description:'',status:'inbox',priority:'medium',dueDate:'',dueTime:'',tags:[],subtasks:[],recurrence:'none',reminderMinutes:0,estimatedMinutes:30,project:'',createdAt:new Date().toISOString()});quickTitle.value='';toast.add({severity:'success',summary:'Guardada en la bandeja',detail:'Podés organizarla cuando quieras.',life:1800})}
function reset(){editingId.value=null;Object.assign(form,{title:'',description:'',status:'todo',priority:'medium',dueDate:todayKey(),dueTime:'',tagsText:'',subtasks:[],recurrence:'none',reminderMinutes:30,estimatedMinutes:30,project:''})}
function create(){reset();visible.value=true}
function edit(item:PersonalTask){editingId.value=item.id;Object.assign(form,{...item,tagsText:item.tags.join(', '),subtasks:item.subtasks.map(x=>({...x}))});visible.value=true}
function addSubtask(){if(!subtaskText.value.trim())return;form.subtasks.push({id:createId('subtask'),title:subtaskText.value.trim(),completed:false});subtaskText.value=''}
function save(){if(!form.title.trim()){toast.add({severity:'warn',summary:'Falta el título',detail:'Escribí qué necesitás hacer.',life:2400});return}const old=store.data.tasks.find(item=>item.id===editingId.value);store.upsert('tasks',{id:editingId.value??createId('task'),title:form.title.trim(),description:form.description.trim(),status:form.status,priority:form.priority,dueDate:form.dueDate,dueTime:form.dueTime,tags:form.tagsText.split(',').map(x=>x.trim()).filter(Boolean),subtasks:form.subtasks.map(x=>({...x})),recurrence:form.recurrence,reminderMinutes:form.reminderMinutes,estimatedMinutes:form.estimatedMinutes,project:form.project.trim(),createdAt:old?.createdAt??new Date().toISOString(),completedAt:form.status==='done'?(old?.completedAt??new Date().toISOString()):undefined});visible.value=false;toast.add({severity:'success',summary:'Tarea guardada',detail:'Tu planificación quedó actualizada.',life:2000})}
function toggleDone(item:PersonalTask){const done=item.status==='done';store.upsert('tasks',{...item,status:done?'todo':'done',completedAt:done?undefined:new Date().toISOString()})}
function move(item:PersonalTask,status:TaskStatus){store.upsert('tasks',{...item,status,completedAt:status==='done'?new Date().toISOString():undefined})}
function toggleSubtask(item:PersonalTask,id:string){store.upsert('tasks',{...item,subtasks:item.subtasks.map(x=>x.id===id?{...x,completed:!x.completed}:x)})}
function remove(item:PersonalTask){confirm.require({message:`¿Eliminar “${item.title}”?`,header:'Eliminar tarea',icon:'pi pi-exclamation-triangle',rejectProps:{label:'Cancelar',severity:'secondary',outlined:true},acceptProps:{label:'Eliminar',severity:'danger'},accept:()=>store.remove('tasks',item.id)})}
const priorityLabel=(value:TaskPriority)=>priorities.find(x=>x.value===value)?.label??value;const prioritySeverity=(value:TaskPriority)=>value==='urgent'?'danger':value==='high'?'warn':value==='low'?'secondary':'info'
</script>

<template><section class="page-container"><PageHeader eyebrow="Acción y prioridades" title="Tareas" description="Capturá pendientes, organizá subtareas y decidí qué merece tu atención hoy."><div class="header-actions"><RouterLink to="/enfoque"><Button label="Modo enfoque" icon="pi pi-stopwatch" severity="secondary" outlined/></RouterLink><Button label="Nueva tarea" icon="pi pi-plus" @click="create"/></div></PageHeader>
<div class="quick-capture"><span><i class="pi pi-inbox"/></span><InputText v-model="quickTitle" placeholder="Anotá algo rápido y organizalo después..." @keyup.enter="quickAdd"/><Button label="Guardar en bandeja" icon="pi pi-arrow-right" @click="quickAdd"/></div>
<div class="metrics-grid task-metrics"><article class="mini-stat"><span class="row-icon violet"><i class="pi pi-sun"/></span><div><strong>{{todayCount}}</strong><small>para hoy</small></div></article><article class="mini-stat"><span class="row-icon blue"><i class="pi pi-inbox"/></span><div><strong>{{inboxCount}}</strong><small>sin organizar</small></div></article><article class="mini-stat"><span class="row-icon rose"><i class="pi pi-exclamation-circle"/></span><div><strong>{{overdueCount}}</strong><small>vencidas</small></div></article><article class="mini-stat"><span class="row-icon green"><i class="pi pi-check-circle"/></span><div><strong>{{completedWeek}}</strong><small>completadas en 7 días</small></div></article></div>
<div class="task-toolbar"><div class="segment-control compact"><button :class="{active:view==='today'}" @click="view='today'">Hoy</button><button :class="{active:view==='week'}" @click="view='week'">Próximos 7 días</button><button :class="{active:view==='inbox'}" @click="view='inbox'">Bandeja</button><button :class="{active:view==='all'}" @click="view='all'">Todas</button></div><span class="search-box"><i class="pi pi-search"/><InputText v-model="search" placeholder="Buscar tarea..."/></span><Select v-model="priorityFilter" :options="[{label:'Todas las prioridades',value:'all'},...priorities]" option-label="label" option-value="value"/></div>
<div v-if="filtered.length" class="task-list"><Card v-for="item in filtered" :key="item.id" :class="['task-card',{done:item.status==='done',overdue:item.status!=='done'&&item.dueDate&&item.dueDate<store.today}]"><template #content><button class="task-check" @click="toggleDone(item)"><i :class="item.status==='done'?'pi pi-check-circle':'pi pi-circle'"/></button><div class="task-content"><div class="task-title-row"><h3>{{item.title}}</h3><Tag :value="priorityLabel(item.priority)" :severity="prioritySeverity(item.priority)" rounded/><Tag v-if="item.status==='doing'" value="En curso" severity="info" rounded/></div><p v-if="item.description">{{item.description}}</p><div class="task-meta"><span v-if="item.dueDate"><i class="pi pi-calendar"/> {{formatDate(item.dueDate,'dd MMM')}}<template v-if="item.dueTime"> · {{item.dueTime}}</template></span><span v-if="item.estimatedMinutes"><i class="pi pi-clock"/> {{item.estimatedMinutes}} min</span><span v-if="item.project"><i class="pi pi-folder"/> {{item.project}}</span><span v-if="item.recurrence!=='none'"><i class="pi pi-refresh"/> {{item.recurrence==='daily'?'Diaria':item.recurrence==='weekly'?'Semanal':'Mensual'}}</span></div><div v-if="item.tags.length" class="chip-list"><span v-for="tag in item.tags" :key="tag">#{{tag}}</span></div><div v-if="item.subtasks.length" class="subtask-list"><label v-for="subtask in item.subtasks" :key="subtask.id"><Checkbox :model-value="subtask.completed" binary @update:model-value="toggleSubtask(item,subtask.id)"/><span :class="{done:subtask.completed}">{{subtask.title}}</span></label></div></div><div class="task-menu"><Button v-if="item.status==='inbox'" label="Planificar" icon="pi pi-arrow-right" size="small" text @click="move(item,'todo')"/><Button v-else-if="item.status==='todo'" label="Empezar" icon="pi pi-play" size="small" text @click="move(item,'doing')"/><RouterLink v-if="item.status!=='done'" :to="`/enfoque?task=${item.id}`"><Button icon="pi pi-stopwatch" text rounded title="Enfocar"/></RouterLink><Button icon="pi pi-pencil" text rounded @click="edit(item)"/><Button icon="pi pi-trash" text rounded severity="danger" @click="remove(item)"/></div></template></Card></div><EmptyState v-else icon="pi pi-check-square" title="No hay tareas en esta vista" description="Creá una tarea o cambiá los filtros para seguir organizando tu día."><Button label="Nueva tarea" icon="pi pi-plus" @click="create"/></EmptyState>
<Dialog v-model:visible="visible" modal :header="editingId?'Editar tarea':'Nueva tarea'" :style="{width:'min(95vw,52rem)'}"><div class="form-grid"><label class="field full"><span>Título</span><InputText v-model="form.title" placeholder="¿Qué necesitás hacer?" autofocus/></label><label class="field full"><span>Descripción</span><Textarea v-model="form.description" rows="3" auto-resize/></label><label class="field"><span>Estado</span><Select v-model="form.status" :options="statuses" option-label="label" option-value="value"/></label><label class="field"><span>Prioridad</span><Select v-model="form.priority" :options="priorities" option-label="label" option-value="value"/></label><label class="field"><span>Fecha límite</span><InputText v-model="form.dueDate" type="date"/></label><label class="field"><span>Hora</span><InputText v-model="form.dueTime" type="time"/></label><label class="field"><span>Proyecto o área</span><InputText v-model="form.project" placeholder="Trabajo, hogar, estudio..."/></label><label class="field"><span>Tiempo estimado</span><InputNumber v-model="form.estimatedMinutes" suffix=" min" :min="5"/></label><label class="field"><span>Repetición</span><Select v-model="form.recurrence" :options="recurrences" option-label="label" option-value="value"/></label><label class="field"><span>Recordar antes</span><InputNumber v-model="form.reminderMinutes" suffix=" min" :min="0"/></label><label class="field full"><span>Etiquetas</span><InputText v-model="form.tagsText" placeholder="urgente, casa, llamada"/></label><div class="field full"><span>Subtareas</span><div class="subtask-editor"><InputText v-model="subtaskText" placeholder="Agregar un paso..." @keyup.enter="addSubtask"/><Button icon="pi pi-plus" @click="addSubtask"/></div><div class="subtask-draft"><label v-for="subtask in form.subtasks" :key="subtask.id"><Checkbox v-model="subtask.completed" binary/><InputText v-model="subtask.title"/><Button icon="pi pi-times" text rounded severity="danger" @click="form.subtasks=form.subtasks.filter(x=>x.id!==subtask.id)"/></label></div></div></div><template #footer><Button label="Cancelar" text severity="secondary" @click="visible=false"/><Button label="Guardar tarea" icon="pi pi-check" @click="save"/></template></Dialog>
</section></template>
