<script setup lang="ts">
import { computed, reactive, ref } from 'vue'
import Button from 'primevue/button'
import Card from 'primevue/card'
import Dialog from 'primevue/dialog'
import InputNumber from 'primevue/inputnumber'
import InputText from 'primevue/inputtext'
import Select from 'primevue/select'
import ToggleSwitch from 'primevue/toggleswitch'
import Tag from 'primevue/tag'
import { useConfirm } from 'primevue/useconfirm'
import { useToast } from 'primevue/usetoast'
import EmptyState from '@/components/EmptyState.vue'
import ModuleTabs from '@/components/ModuleTabs.vue'
import PageHeader from '@/components/PageHeader.vue'
import { useAppStore } from '@/stores/app'
import type { InstallmentPlan, RecurringTransaction, Subscription, TransactionType } from '@/types/domain'
import { formatCurrency, formatDate, todayKey } from '@/utils/date'
import { createId } from '@/utils/id'
import { financeTabs } from './navigation'

const store=useAppStore();const toast=useToast();const confirm=useConfirm();const activeSection=ref<'recurring'|'subscriptions'|'installments'>('recurring')
const recurringVisible=ref(false);const subscriptionVisible=ref(false);const installmentVisible=ref(false);const editingId=ref<string|null>(null)
const categories=['Servicios','Hogar','Salud','Transporte','Educación','Ocio','Ingresos','Otros'];const methods=['Débito automático','Crédito','Transferencia','Efectivo','Billetera virtual']
const recurringForm=reactive({type:'expense' as TransactionType,title:'',amount:0,category:'Servicios',frequency:'monthly' as 'weekly'|'monthly'|'yearly',dayOfMonth:1,nextDate:todayKey(),active:true,paymentMethod:methods[0]})
const subscriptionForm=reactive({name:'',amount:0,frequency:'monthly' as 'monthly'|'yearly',nextBilling:todayKey(),category:'Ocio',active:true,url:''})
const installmentForm=reactive({title:'',totalAmount:0,installments:1,paidInstallments:0,installmentAmount:0,nextDueDate:todayKey(),card:''})
const recurringTotal=computed(()=>store.data.recurringTransactions.filter(x=>x.active&&x.type==='expense'&&x.frequency==='monthly').reduce((s,x)=>s+x.amount,0));const subscriptionTotal=computed(()=>store.data.subscriptions.filter(x=>x.active).reduce((s,x)=>s+(x.frequency==='monthly'?x.amount:x.amount/12),0));const installmentTotal=computed(()=>store.data.installmentPlans.filter(x=>x.paidInstallments<x.installments).reduce((s,x)=>s+x.installmentAmount,0))
function openRecurring(item?:RecurringTransaction){editingId.value=item?.id??null;Object.assign(recurringForm,item??{type:'expense',title:'',amount:0,category:'Servicios',frequency:'monthly',dayOfMonth:1,nextDate:todayKey(),active:true,paymentMethod:methods[0]});recurringVisible.value=true}
function saveRecurring(){if(!recurringForm.title.trim()||recurringForm.amount<=0){toast.add({severity:'warn',summary:'Faltan datos',detail:'Completá nombre e importe.',life:2500});return}store.upsert('recurringTransactions',{id:editingId.value??createId('recurring'),...recurringForm,title:recurringForm.title.trim()});recurringVisible.value=false;toast.add({severity:'success',summary:'Compromiso guardado',detail:'Se agregó a tu planificación.',life:2200})}
function openSubscription(item?:Subscription){editingId.value=item?.id??null;Object.assign(subscriptionForm,item??{name:'',amount:0,frequency:'monthly',nextBilling:todayKey(),category:'Ocio',active:true,url:''});subscriptionVisible.value=true}
function saveSubscription(){if(!subscriptionForm.name.trim()||subscriptionForm.amount<=0){toast.add({severity:'warn',summary:'Faltan datos',detail:'Completá servicio e importe.',life:2500});return}store.upsert('subscriptions',{id:editingId.value??createId('subscription'),...subscriptionForm,name:subscriptionForm.name.trim()});subscriptionVisible.value=false;toast.add({severity:'success',summary:'Suscripción guardada',detail:'El próximo cobro quedó agendado.',life:2200})}
function openInstallment(item?:InstallmentPlan){editingId.value=item?.id??null;Object.assign(installmentForm,item??{title:'',totalAmount:0,installments:1,paidInstallments:0,installmentAmount:0,nextDueDate:todayKey(),card:''});installmentVisible.value=true}
function saveInstallment(){if(!installmentForm.title.trim()||installmentForm.totalAmount<=0||installmentForm.installments<1){toast.add({severity:'warn',summary:'Faltan datos',detail:'Completá compra, total y cuotas.',life:2500});return}if(!installmentForm.installmentAmount)installmentForm.installmentAmount=installmentForm.totalAmount/installmentForm.installments;store.upsert('installmentPlans',{id:editingId.value??createId('installment'),...installmentForm,title:installmentForm.title.trim()});installmentVisible.value=false;toast.add({severity:'success',summary:'Plan de cuotas guardado',detail:'Podés seguir cada vencimiento.',life:2200})}
function remove(collection:'recurringTransactions'|'subscriptions'|'installmentPlans',id:string,title:string){confirm.require({message:`¿Eliminar “${title}”?`,header:'Eliminar compromiso',icon:'pi pi-exclamation-triangle',rejectProps:{label:'Cancelar',severity:'secondary',outlined:true},acceptProps:{label:'Eliminar',severity:'danger'},accept:()=>store.remove(collection,id)})}
function markInstallmentPaid(item:InstallmentPlan){if(item.paidInstallments>=item.installments)return;store.upsert('installmentPlans',{...item,paidInstallments:item.paidInstallments+1})}
</script>

<template><section class="page-container"><PageHeader eyebrow="Pagos futuros" title="Compromisos" description="Centralizá gastos fijos, suscripciones y compras en cuotas antes de que lleguen."><Button label="Agregar compromiso" icon="pi pi-plus" @click="activeSection==='recurring'?openRecurring():activeSection==='subscriptions'?openSubscription():openInstallment()"/></PageHeader><ModuleTabs :tabs="financeTabs"/>
<div class="segment-control"><button :class="{active:activeSection==='recurring'}" @click="activeSection='recurring'"><i class="pi pi-refresh"/> Recurrentes <b>{{formatCurrency(recurringTotal,store.data.settings.currency)}}</b></button><button :class="{active:activeSection==='subscriptions'}" @click="activeSection='subscriptions'"><i class="pi pi-star"/> Suscripciones <b>{{formatCurrency(subscriptionTotal,store.data.settings.currency)}}</b></button><button :class="{active:activeSection==='installments'}" @click="activeSection='installments'"><i class="pi pi-credit-card"/> Cuotas <b>{{formatCurrency(installmentTotal,store.data.settings.currency)}}</b></button></div>
<div v-if="activeSection==='recurring'"><div v-if="store.data.recurringTransactions.length" class="entity-grid"><Card v-for="item in store.data.recurringTransactions" :key="item.id" class="entity-card"><template #content><div class="entity-header"><span :class="['row-icon',item.type==='income'?'green':'rose']"><i class="pi pi-refresh"/></span><div><h3>{{item.title}}</h3><p>{{item.category}} · {{item.frequency==='monthly'?'Mensual':item.frequency==='weekly'?'Semanal':'Anual'}}</p></div><Tag :value="item.active?'Activo':'Pausado'" :severity="item.active?'success':'secondary'"/></div><div class="entity-meta"><span><i class="pi pi-calendar"/> Próximo: {{formatDate(item.nextDate,'dd/MM/yyyy')}}</span><span><i class="pi pi-wallet"/> {{formatCurrency(item.amount,store.data.settings.currency)}}</span></div><div class="entity-actions"><Button label="Editar" icon="pi pi-pencil" text @click="openRecurring(item)"/><Button label="Eliminar" icon="pi pi-trash" text severity="danger" @click="remove('recurringTransactions',item.id,item.title)"/></div></template></Card></div><EmptyState v-else icon="pi pi-refresh" title="Sin movimientos recurrentes" description="Registrá alquiler, servicios, sueldo u otros movimientos repetitivos."/></div>
<div v-else-if="activeSection==='subscriptions'"><div v-if="store.data.subscriptions.length" class="entity-grid"><Card v-for="item in store.data.subscriptions" :key="item.id" class="entity-card"><template #content><div class="entity-header"><span class="row-icon violet"><i class="pi pi-star"/></span><div><h3>{{item.name}}</h3><p>{{item.category}} · {{item.frequency==='monthly'?'Mensual':'Anual'}}</p></div><Tag :value="item.active?'Activa':'Pausada'" :severity="item.active?'success':'secondary'"/></div><div class="entity-meta"><span><i class="pi pi-calendar"/> Cobra {{formatDate(item.nextBilling,'dd/MM/yyyy')}}</span><span><i class="pi pi-wallet"/> {{formatCurrency(item.amount,store.data.settings.currency)}}</span></div><div class="entity-actions"><Button label="Editar" icon="pi pi-pencil" text @click="openSubscription(item)"/><Button label="Eliminar" icon="pi pi-trash" text severity="danger" @click="remove('subscriptions',item.id,item.name)"/></div></template></Card></div><EmptyState v-else icon="pi pi-star" title="Sin suscripciones" description="Agregá plataformas, membresías y servicios digitales."/></div>
<div v-else><div v-if="store.data.installmentPlans.length" class="entity-grid"><Card v-for="item in store.data.installmentPlans" :key="item.id" class="entity-card"><template #content><div class="entity-header"><span class="row-icon blue"><i class="pi pi-credit-card"/></span><div><h3>{{item.title}}</h3><p>{{item.card||'Sin tarjeta indicada'}}</p></div><Tag :value="`${item.paidInstallments}/${item.installments} pagadas`" :severity="item.paidInstallments===item.installments?'success':'info'"/></div><div class="entity-meta"><span><i class="pi pi-calendar"/> Próxima: {{formatDate(item.nextDueDate,'dd/MM/yyyy')}}</span><span><i class="pi pi-wallet"/> {{formatCurrency(item.installmentAmount,store.data.settings.currency)}}</span></div><div class="entity-actions"><Button label="Marcar cuota pagada" icon="pi pi-check" text severity="success" :disabled="item.paidInstallments>=item.installments" @click="markInstallmentPaid(item)"/><Button label="Editar" icon="pi pi-pencil" text @click="openInstallment(item)"/><Button icon="pi pi-trash" text severity="danger" @click="remove('installmentPlans',item.id,item.title)"/></div></template></Card></div><EmptyState v-else icon="pi pi-credit-card" title="Sin compras en cuotas" description="Cargá una compra y seguí cuánto falta pagar."/></div>
<Dialog v-model:visible="recurringVisible" modal header="Movimiento recurrente" :style="{width:'min(92vw,36rem)'}"><div class="form-grid"><label class="field"><span>Tipo</span><Select v-model="recurringForm.type" :options="[{label:'Gasto',value:'expense'},{label:'Ingreso',value:'income'}]" option-label="label" option-value="value"/></label><label class="field"><span>Nombre</span><InputText v-model="recurringForm.title"/></label><label class="field"><span>Importe</span><InputNumber v-model="recurringForm.amount" mode="currency" :currency="store.data.settings.currency" locale="es-AR"/></label><label class="field"><span>Categoría</span><Select v-model="recurringForm.category" :options="categories" editable/></label><label class="field"><span>Frecuencia</span><Select v-model="recurringForm.frequency" :options="[{label:'Semanal',value:'weekly'},{label:'Mensual',value:'monthly'},{label:'Anual',value:'yearly'}]" option-label="label" option-value="value"/></label><label class="field"><span>Próxima fecha</span><InputText v-model="recurringForm.nextDate" type="date"/></label><label class="field full"><span>Forma de pago</span><Select v-model="recurringForm.paymentMethod" :options="methods"/></label><label class="switch-field full"><span><strong>Activo</strong><small>Se tendrá en cuenta en las proyecciones.</small></span><ToggleSwitch v-model="recurringForm.active"/></label></div><template #footer><Button label="Cancelar" text @click="recurringVisible=false"/><Button label="Guardar" icon="pi pi-check" @click="saveRecurring"/></template></Dialog>
<Dialog v-model:visible="subscriptionVisible" modal header="Suscripción" :style="{width:'min(92vw,36rem)'}"><div class="form-grid"><label class="field full"><span>Servicio</span><InputText v-model="subscriptionForm.name"/></label><label class="field"><span>Importe</span><InputNumber v-model="subscriptionForm.amount" mode="currency" :currency="store.data.settings.currency" locale="es-AR"/></label><label class="field"><span>Frecuencia</span><Select v-model="subscriptionForm.frequency" :options="[{label:'Mensual',value:'monthly'},{label:'Anual',value:'yearly'}]" option-label="label" option-value="value"/></label><label class="field"><span>Próximo cobro</span><InputText v-model="subscriptionForm.nextBilling" type="date"/></label><label class="field"><span>Categoría</span><Select v-model="subscriptionForm.category" :options="categories" editable/></label><label class="field full"><span>Sitio web</span><InputText v-model="subscriptionForm.url" placeholder="https://..."/></label><label class="switch-field full"><span><strong>Activa</strong><small>Incluida en el costo mensual estimado.</small></span><ToggleSwitch v-model="subscriptionForm.active"/></label></div><template #footer><Button label="Cancelar" text @click="subscriptionVisible=false"/><Button label="Guardar" icon="pi pi-check" @click="saveSubscription"/></template></Dialog>
<Dialog v-model:visible="installmentVisible" modal header="Compra en cuotas" :style="{width:'min(92vw,36rem)'}"><div class="form-grid"><label class="field full"><span>Compra</span><InputText v-model="installmentForm.title"/></label><label class="field"><span>Total</span><InputNumber v-model="installmentForm.totalAmount" mode="currency" :currency="store.data.settings.currency" locale="es-AR"/></label><label class="field"><span>Cantidad de cuotas</span><InputNumber v-model="installmentForm.installments" :min="1"/></label><label class="field"><span>Cuotas ya pagadas</span><InputNumber v-model="installmentForm.paidInstallments" :min="0" :max="installmentForm.installments"/></label><label class="field"><span>Importe por cuota</span><InputNumber v-model="installmentForm.installmentAmount" mode="currency" :currency="store.data.settings.currency" locale="es-AR"/></label><label class="field"><span>Próximo vencimiento</span><InputText v-model="installmentForm.nextDueDate" type="date"/></label><label class="field full"><span>Tarjeta</span><InputText v-model="installmentForm.card" placeholder="Ej. Visa Banco..."/></label></div><template #footer><Button label="Cancelar" text @click="installmentVisible=false"/><Button label="Guardar" icon="pi pi-check" @click="saveInstallment"/></template></Dialog>
</section></template>
