<script setup lang="ts">
import { computed, reactive, ref } from 'vue'
import Button from 'primevue/button'
import Card from 'primevue/card'
import Dialog from 'primevue/dialog'
import InputNumber from 'primevue/inputnumber'
import InputText from 'primevue/inputtext'
import Select from 'primevue/select'
import ProgressBar from 'primevue/progressbar'
import Tag from 'primevue/tag'
import { useConfirm } from 'primevue/useconfirm'
import { useToast } from 'primevue/usetoast'
import EmptyState from '@/components/EmptyState.vue'
import ModuleTabs from '@/components/ModuleTabs.vue'
import PageHeader from '@/components/PageHeader.vue'
import { useAppStore } from '@/stores/app'
import type { Debt, SavingsGoal } from '@/types/domain'
import { formatCurrency, formatDate, percentage, todayKey } from '@/utils/date'
import { createId } from '@/utils/id'
import { financeTabs } from './navigation'

const store=useAppStore();const toast=useToast();const confirm=useConfirm();const section=ref<'goals'|'debts'>('goals');const goalVisible=ref(false);const debtVisible=ref(false);const amountVisible=ref(false);const editingId=ref<string|null>(null);const actionTarget=ref<{type:'goal'|'debt';id:string;title:string}|null>(null);const actionAmount=ref(0)
const colors=['#6d5dfc','#0ea5e9','#14b8a6','#f59e0b','#f43f5e','#6366f1']
const goalForm=reactive({title:'',targetAmount:0,currentAmount:0,targetDate:todayKey(),color:colors[0]})
const debtForm=reactive({name:'',totalAmount:0,remainingAmount:0,interestRate:0,minimumPayment:0,dueDay:10,type:'card' as 'card'|'loan'|'personal',status:'active' as 'active'|'paid'})
const saved=computed(()=>store.data.savingsGoals.reduce((s,x)=>s+x.currentAmount,0));const goalTotal=computed(()=>store.data.savingsGoals.reduce((s,x)=>s+x.targetAmount,0));const debtRemaining=computed(()=>store.data.debts.filter(x=>x.status==='active').reduce((s,x)=>s+x.remainingAmount,0));const minPayments=computed(()=>store.data.debts.filter(x=>x.status==='active').reduce((s,x)=>s+x.minimumPayment,0))
function openGoal(item?:SavingsGoal){editingId.value=item?.id??null;Object.assign(goalForm,item??{title:'',targetAmount:0,currentAmount:0,targetDate:todayKey(),color:colors[0]});goalVisible.value=true}
function saveGoal(){if(!goalForm.title.trim()||goalForm.targetAmount<=0){toast.add({severity:'warn',summary:'Meta incompleta',detail:'Indicá nombre y monto objetivo.',life:2600});return}store.upsert('savingsGoals',{id:editingId.value??createId('goal'),...goalForm,title:goalForm.title.trim()});goalVisible.value=false;toast.add({severity:'success',summary:'Meta guardada',detail:'Tu objetivo ya aparece en el seguimiento.',life:2200})}
function openDebt(item?:Debt){editingId.value=item?.id??null;Object.assign(debtForm,item??{name:'',totalAmount:0,remainingAmount:0,interestRate:0,minimumPayment:0,dueDay:10,type:'card',status:'active'});debtVisible.value=true}
function saveDebt(){if(!debtForm.name.trim()||debtForm.totalAmount<=0){toast.add({severity:'warn',summary:'Deuda incompleta',detail:'Indicá nombre y monto total.',life:2600});return}if(!debtForm.remainingAmount)debtForm.remainingAmount=debtForm.totalAmount;store.upsert('debts',{id:editingId.value??createId('debt'),...debtForm,name:debtForm.name.trim()});debtVisible.value=false;toast.add({severity:'success',summary:'Deuda guardada',detail:'El plan de reducción quedó actualizado.',life:2200})}
function openAmount(type:'goal'|'debt',id:string,title:string){actionTarget.value={type,id,title};actionAmount.value=0;amountVisible.value=true}
function applyAmount(){if(!actionTarget.value||actionAmount.value<=0)return;if(actionTarget.value.type==='goal'){const item=store.data.savingsGoals.find(x=>x.id===actionTarget.value!.id);if(item)store.upsert('savingsGoals',{...item,currentAmount:Math.min(item.targetAmount,item.currentAmount+actionAmount.value)})}else{const item=store.data.debts.find(x=>x.id===actionTarget.value!.id);if(item){const remaining=Math.max(0,item.remainingAmount-actionAmount.value);store.upsert('debts',{...item,remainingAmount:remaining,status:remaining===0?'paid':'active'})}}amountVisible.value=false}
function remove(collection:'savingsGoals'|'debts',id:string,title:string){confirm.require({message:`¿Eliminar “${title}”?`,header:'Confirmar eliminación',icon:'pi pi-exclamation-triangle',rejectProps:{label:'Cancelar',severity:'secondary',outlined:true},acceptProps:{label:'Eliminar',severity:'danger'},accept:()=>store.remove(collection,id)})}
</script>

<template><section class="page-container"><PageHeader eyebrow="Objetivos financieros" title="Metas y deudas" description="Avanzá hacia tus ahorros y reducí obligaciones con un seguimiento claro."><Button :label="section==='goals'?'Nueva meta':'Nueva deuda'" icon="pi pi-plus" @click="section==='goals'?openGoal():openDebt()"/></PageHeader><ModuleTabs :tabs="financeTabs"/>
<div class="metrics-grid"><article class="metric-card"><span class="metric-card__icon green"><i class="pi pi-flag"/></span><div><small>Ahorro acumulado</small><strong>{{formatCurrency(saved,store.data.settings.currency)}}</strong><p>de {{formatCurrency(goalTotal,store.data.settings.currency)}} en objetivos</p></div></article><article class="metric-card"><span class="metric-card__icon rose"><i class="pi pi-credit-card"/></span><div><small>Deuda pendiente</small><strong>{{formatCurrency(debtRemaining,store.data.settings.currency)}}</strong><p>{{formatCurrency(minPayments,store.data.settings.currency)}} de pago mínimo</p></div></article></div>
<div class="segment-control compact"><button :class="{active:section==='goals'}" @click="section='goals'"><i class="pi pi-flag"/> Metas de ahorro</button><button :class="{active:section==='debts'}" @click="section='debts'"><i class="pi pi-credit-card"/> Deudas</button></div>
<div v-if="section==='goals'"><div v-if="store.data.savingsGoals.length" class="goal-grid"><Card v-for="item in store.data.savingsGoals" :key="item.id" class="goal-card"><template #content><div class="goal-head"><span :style="{background:item.color}"><i class="pi pi-flag"/></span><div><h3>{{item.title}}</h3><small>Objetivo para {{formatDate(item.targetDate,'dd MMM yyyy')}}</small></div><Tag :value="`${percentage(item.currentAmount,item.targetAmount)}%`" rounded/></div><strong>{{formatCurrency(item.currentAmount,store.data.settings.currency)}} <small>de {{formatCurrency(item.targetAmount,store.data.settings.currency)}}</small></strong><ProgressBar :value="percentage(item.currentAmount,item.targetAmount)" :show-value="false"/><p>Faltan {{formatCurrency(Math.max(0,item.targetAmount-item.currentAmount),store.data.settings.currency)}}</p><div class="entity-actions"><Button label="Aportar" icon="pi pi-plus" severity="success" @click="openAmount('goal',item.id,item.title)"/><Button label="Editar" icon="pi pi-pencil" text @click="openGoal(item)"/><Button icon="pi pi-trash" text severity="danger" @click="remove('savingsGoals',item.id,item.title)"/></div></template></Card></div><EmptyState v-else icon="pi pi-flag" title="Todavía no definiste metas" description="Creá un objetivo, una fecha y registrá cada aporte."/></div>
<div v-else><div v-if="store.data.debts.length" class="entity-grid"><Card v-for="item in store.data.debts" :key="item.id" class="entity-card"><template #content><div class="entity-header"><span :class="['row-icon',item.status==='paid'?'green':'rose']"><i class="pi pi-credit-card"/></span><div><h3>{{item.name}}</h3><p>{{item.type==='card'?'Tarjeta':item.type==='loan'?'Préstamo':'Deuda personal'}} · vence día {{item.dueDay}}</p></div><Tag :value="item.status==='paid'?'Pagada':'Activa'" :severity="item.status==='paid'?'success':'warn'"/></div><div class="debt-progress"><div><small>Pendiente</small><strong>{{formatCurrency(item.remainingAmount,store.data.settings.currency)}}</strong></div><div><small>Pago mínimo</small><strong>{{formatCurrency(item.minimumPayment,store.data.settings.currency)}}</strong></div><div><small>Tasa</small><strong>{{item.interestRate}}%</strong></div></div><ProgressBar :value="100-percentage(item.remainingAmount,item.totalAmount)" :show-value="false"/><div class="entity-actions"><Button label="Registrar pago" icon="pi pi-check" severity="success" :disabled="item.status==='paid'" @click="openAmount('debt',item.id,item.name)"/><Button label="Editar" icon="pi pi-pencil" text @click="openDebt(item)"/><Button icon="pi pi-trash" text severity="danger" @click="remove('debts',item.id,item.name)"/></div></template></Card></div><EmptyState v-else icon="pi pi-credit-card" title="No hay deudas registradas" description="Cargá tarjetas o préstamos para seguir su reducción."/></div>
<Dialog v-model:visible="goalVisible" modal :header="editingId?'Editar meta':'Nueva meta de ahorro'" :style="{width:'min(92vw,36rem)'}"><div class="form-grid"><label class="field full"><span>Objetivo</span><InputText v-model="goalForm.title" placeholder="Ej. Fondo de emergencia"/></label><label class="field"><span>Monto objetivo</span><InputNumber v-model="goalForm.targetAmount" mode="currency" :currency="store.data.settings.currency" locale="es-AR"/></label><label class="field"><span>Ya ahorrado</span><InputNumber v-model="goalForm.currentAmount" mode="currency" :currency="store.data.settings.currency" locale="es-AR"/></label><label class="field full"><span>Fecha objetivo</span><InputText v-model="goalForm.targetDate" type="date"/></label><div class="field full"><span>Color</span><div class="color-picker"><button v-for="color in colors" :key="color" type="button" :style="{background:color}" :class="{selected:goalForm.color===color}" @click="goalForm.color=color"/></div></div></div><template #footer><Button label="Cancelar" text @click="goalVisible=false"/><Button label="Guardar" icon="pi pi-check" @click="saveGoal"/></template></Dialog>
<Dialog v-model:visible="debtVisible" modal :header="editingId?'Editar deuda':'Nueva deuda'" :style="{width:'min(92vw,38rem)'}"><div class="form-grid"><label class="field full"><span>Nombre</span><InputText v-model="debtForm.name" placeholder="Ej. Visa, préstamo personal"/></label><label class="field"><span>Tipo</span><Select v-model="debtForm.type" :options="[{label:'Tarjeta',value:'card'},{label:'Préstamo',value:'loan'},{label:'Personal',value:'personal'}]" option-label="label" option-value="value"/></label><label class="field"><span>Monto total</span><InputNumber v-model="debtForm.totalAmount" mode="currency" :currency="store.data.settings.currency" locale="es-AR"/></label><label class="field"><span>Saldo pendiente</span><InputNumber v-model="debtForm.remainingAmount" mode="currency" :currency="store.data.settings.currency" locale="es-AR"/></label><label class="field"><span>Pago mínimo</span><InputNumber v-model="debtForm.minimumPayment" mode="currency" :currency="store.data.settings.currency" locale="es-AR"/></label><label class="field"><span>Tasa anual</span><InputNumber v-model="debtForm.interestRate" suffix=" %"/></label><label class="field"><span>Día de vencimiento</span><InputNumber v-model="debtForm.dueDay" :min="1" :max="31"/></label></div><template #footer><Button label="Cancelar" text @click="debtVisible=false"/><Button label="Guardar" icon="pi pi-check" @click="saveDebt"/></template></Dialog>
<Dialog v-model:visible="amountVisible" modal :header="actionTarget?.type==='goal'?'Registrar aporte':'Registrar pago'" :style="{width:'min(92vw,28rem)'}"><p class="dialog-copy">{{actionTarget?.title}}</p><label class="field"><span>Importe</span><InputNumber v-model="actionAmount" mode="currency" :currency="store.data.settings.currency" locale="es-AR" :min="0" autofocus/></label><template #footer><Button label="Cancelar" text @click="amountVisible=false"/><Button label="Confirmar" icon="pi pi-check" @click="applyAmount"/></template></Dialog>
</section></template>
