<script setup lang="ts">
import { computed, reactive, ref } from 'vue'
import Button from 'primevue/button'
import Card from 'primevue/card'
import Dialog from 'primevue/dialog'
import InputNumber from 'primevue/inputnumber'
import InputText from 'primevue/inputtext'
import MultiSelect from 'primevue/multiselect'
import Select from 'primevue/select'
import Textarea from 'primevue/textarea'
import Tag from 'primevue/tag'
import ToggleSwitch from 'primevue/toggleswitch'
import { useConfirm } from 'primevue/useconfirm'
import { useToast } from 'primevue/usetoast'
import EmptyState from '@/components/EmptyState.vue'
import ModuleTabs from '@/components/ModuleTabs.vue'
import PageHeader from '@/components/PageHeader.vue'
import { useAppStore } from '@/stores/app'
import type { Medication } from '@/types/domain'
import { formatDate, todayKey } from '@/utils/date'
import { createId } from '@/utils/id'
import { healthTabs } from './navigation'

const store=useAppStore();const toast=useToast();const confirm=useConfirm();const visible=ref(false);const editingId=ref<string|null>(null);const section=ref<'today'|'treatments'|'history'>('today');const stockVisible=ref(false);const stockTarget=ref<Medication|null>(null);const stockValue=ref(0)
const weekdays=[{label:'Domingo',value:0},{label:'Lunes',value:1},{label:'Martes',value:2},{label:'Miércoles',value:3},{label:'Jueves',value:4},{label:'Viernes',value:5},{label:'Sábado',value:6}]
const colors=['#f43f5e','#8b5cf6','#0ea5e9','#14b8a6','#f59e0b','#6366f1']
const form=reactive({name:'',dose:'',timesText:'08:00',days:[0,1,2,3,4,5,6] as number[],notes:'',color:colors[0],active:true,treatmentType:'continuous' as 'continuous'|'temporary'|'asNeeded',startDate:todayKey(),endDate:'',stock:0,stockAlert:5,unit:'comprimidos',doctor:''})
const todayDoses=computed(()=>store.data.medications.filter(item=>item.active&&item.days.includes(store.currentDay)).flatMap(item=>item.times.map(time=>({item,time,log:store.data.medicationLogs.find(log=>log.medicationId===item.id&&log.date===store.today&&log.time===time)}))).sort((a,b)=>a.time.localeCompare(b.time)))
const history=computed(()=>[...store.data.medicationLogs].sort((a,b)=>`${b.date}${b.time}`.localeCompare(`${a.date}${a.time}`)).slice(0,100).map(log=>({log,medication:store.data.medications.find(item=>item.id===log.medicationId)})))
const completion=computed(()=>todayDoses.value.length?Math.round(todayDoses.value.filter(x=>x.log&&x.log.status!=='missed'&&x.log.status!=='skipped').length/todayDoses.value.length*100):0)
function reset(){editingId.value=null;Object.assign(form,{name:'',dose:'',timesText:'08:00',days:[0,1,2,3,4,5,6],notes:'',color:colors[0],active:true,treatmentType:'continuous',startDate:todayKey(),endDate:'',stock:0,stockAlert:5,unit:'comprimidos',doctor:''})}
function create(){reset();visible.value=true}
function edit(item:Medication){editingId.value=item.id;Object.assign(form,{...item,timesText:item.times.join(', '),treatmentType:item.treatmentType??'continuous',startDate:item.startDate??todayKey(),endDate:item.endDate??'',stock:item.stock??0,stockAlert:item.stockAlert??5,unit:item.unit??'comprimidos',doctor:item.doctor??''});visible.value=true}
function save(){const times=[...new Set(form.timesText.split(',').map(x=>x.trim()).filter(x=>/^([01]\d|2[0-3]):[0-5]\d$/.test(x)))].sort();if(!form.name.trim()||!form.dose.trim()||(form.treatmentType!=='asNeeded'&&!times.length)||!form.days.length){toast.add({severity:'warn',summary:'Revisá la medicación',detail:'Completá nombre, dosis, días y horarios.',life:3000});return}const previous=store.data.medications.find(x=>x.id===editingId.value);store.upsertMedication({id:editingId.value??createId('medication'),name:form.name.trim(),dose:form.dose.trim(),times,days:[...form.days].sort(),notes:form.notes.trim(),color:form.color,active:form.active,createdAt:previous?.createdAt??new Date().toISOString(),treatmentType:form.treatmentType,startDate:form.startDate,endDate:form.endDate,stock:form.stock,stockAlert:form.stockAlert,unit:form.unit,doctor:form.doctor.trim()});visible.value=false;toast.add({severity:'success',summary:'Medicación guardada',detail:'El tratamiento quedó actualizado.',life:2200})}
function setStatus(entry:typeof todayDoses.value[number],status:'taken'|'late'|'missed'|'skipped'){const existing=entry.log;if(existing){store.remove('medicationLogs',existing.id);if(existing.status===status)return}store.data.medicationLogs.push({id:createId('medlog'),medicationId:entry.item.id,date:store.today,time:entry.time,takenAt:new Date().toISOString(),status});if(status==='taken'||status==='late')store.updateMedicationStock(entry.item.id,-1)}
function remove(item:Medication){confirm.require({message:`¿Eliminar ${item.name} y su historial?`,header:'Eliminar medicación',icon:'pi pi-exclamation-triangle',rejectProps:{label:'Cancelar',severity:'secondary',outlined:true},acceptProps:{label:'Eliminar',severity:'danger'},accept:()=>store.removeMedication(item.id)})}
function openStock(item:Medication){stockTarget.value=item;stockValue.value=item.stock??0;stockVisible.value=true}
function saveStock(){if(stockTarget.value)store.upsertMedication({...stockTarget.value,stock:stockValue.value});stockVisible.value=false}
const dayText=(days:number[])=>days.length===7?'Todos los días':weekdays.filter(day=>days.includes(day.value)).map(day=>day.label.slice(0,3)).join(', ')
const statusLabel=(status?:string)=>status==='late'?'Con retraso':status==='missed'?'Omitida':status==='skipped'?'Saltada':'Tomada'
</script>

<template><section class="page-container"><PageHeader eyebrow="Tratamientos y tomas" title="Medicación" description="Organizá horarios, stock, duración del tratamiento e historial de cumplimiento."><Button label="Agregar medicación" icon="pi pi-plus" @click="create"/></PageHeader><ModuleTabs :tabs="healthTabs"/>
<div class="segment-control"><button :class="{active:section==='today'}" @click="section='today'"><i class="pi pi-sun"/> Hoy <b>{{completion}}%</b></button><button :class="{active:section==='treatments'}" @click="section='treatments'"><i class="pi pi-box"/> Tratamientos <b>{{store.data.medications.length}}</b></button><button :class="{active:section==='history'}" @click="section='history'"><i class="pi pi-history"/> Historial <b>{{store.data.medicationLogs.length}}</b></button></div>
<div v-if="section==='today'"><div class="medication-progress"><div><span class="eyebrow">Progreso de hoy</span><h2>{{todayDoses.filter(x=>x.log).length}} de {{todayDoses.length}} tomas registradas</h2><p>Podés indicar si fue tomada, retrasada, omitida o saltada.</p></div><strong>{{completion}}%</strong></div><div v-if="todayDoses.length" class="dose-timeline"><article v-for="entry in todayDoses" :key="`${entry.item.id}-${entry.time}`" :class="{completed:entry.log}"><div class="dose-time"><strong>{{entry.time}}</strong><span :style="{background:entry.item.color}"/></div><div class="dose-body"><span class="color-icon" :style="{background:entry.item.color}"><i class="pi pi-heart-fill"/></span><div><h3>{{entry.item.name}}</h3><p>{{entry.item.dose}}<template v-if="entry.item.stock!==undefined"> · Stock: {{entry.item.stock}} {{entry.item.unit}}</template></p><small v-if="entry.item.notes">{{entry.item.notes}}</small></div><Tag v-if="entry.log" :value="statusLabel(entry.log.status)" :severity="entry.log.status==='missed'?'danger':entry.log.status==='skipped'?'secondary':entry.log.status==='late'?'warn':'success'" rounded/></div><div class="dose-actions"><Button label="Tomada" icon="pi pi-check" severity="success" :outlined="entry.log?.status!=='taken'" @click="setStatus(entry,'taken')"/><Button label="Retrasada" icon="pi pi-clock" severity="warn" text @click="setStatus(entry,'late')"/><Button label="Omitida" icon="pi pi-times" severity="danger" text @click="setStatus(entry,'missed')"/><Button label="Saltar" icon="pi pi-forward" severity="secondary" text @click="setStatus(entry,'skipped')"/></div></article></div><EmptyState v-else icon="pi pi-heart" title="No hay tomas programadas hoy" description="Agregá una medicación y elegí los días y horarios."/></div>
<div v-else-if="section==='treatments'"><div v-if="store.data.medications.length" class="entity-grid"><Card v-for="item in store.data.medications" :key="item.id" class="entity-card medication-card"><template #content><div class="entity-header"><span class="color-icon" :style="{background:item.color}"><i class="pi pi-heart-fill"/></span><div><h3>{{item.name}}</h3><p>{{item.dose}}</p></div><Tag :value="item.active?'Activa':'Pausada'" :severity="item.active?'success':'secondary'"/></div><div class="entity-meta"><span><i class="pi pi-clock"/> {{item.treatmentType==='asNeeded'?'Según necesidad':item.times.join(' · ')}}</span><span><i class="pi pi-calendar"/> {{dayText(item.days)}}</span><span v-if="item.startDate"><i class="pi pi-hourglass"/> Desde {{formatDate(item.startDate,'dd/MM/yyyy')}}<template v-if="item.endDate"> hasta {{formatDate(item.endDate,'dd/MM/yyyy')}}</template></span></div><div :class="['stock-box',{low:item.stock!==undefined&&item.stockAlert!==undefined&&item.stock<=item.stockAlert}]"><span><i class="pi pi-box"/><strong>{{item.stock??0}}</strong> {{item.unit??'unidades'}}</span><small v-if="item.stockAlert!==undefined">Aviso al llegar a {{item.stockAlert}}</small><Button label="Actualizar" size="small" text @click="openStock(item)"/></div><p v-if="item.doctor" class="note"><i class="pi pi-user"/> Indicado por {{item.doctor}}</p><p v-if="item.notes" class="note">{{item.notes}}</p><div class="entity-actions"><Button label="Editar" icon="pi pi-pencil" text @click="edit(item)"/><Button label="Eliminar" icon="pi pi-trash" text severity="danger" @click="remove(item)"/></div></template></Card></div><EmptyState v-else icon="pi pi-box" title="No hay tratamientos cargados" description="Registrá tu primera medicación con stock y duración."/></div>
<div v-else><Card class="content-card"><template #title><div class="card-title"><span>Historial de tomas</span><Tag :value="`${history.length} registros`" rounded/></div></template><template #content><div v-if="history.length" class="history-list"><article v-for="entry in history" :key="entry.log.id"><span :class="['history-status',entry.log.status??'taken']"><i :class="entry.log.status==='missed'?'pi pi-times':entry.log.status==='skipped'?'pi pi-forward':entry.log.status==='late'?'pi pi-clock':'pi pi-check'"/></span><div><strong>{{entry.medication?.name??'Medicación eliminada'}}</strong><small>{{formatDate(entry.log.date,'dd/MM/yyyy')}} · {{entry.log.time}} · {{statusLabel(entry.log.status)}}</small></div><Tag :value="statusLabel(entry.log.status)" :severity="entry.log.status==='missed'?'danger':entry.log.status==='skipped'?'secondary':entry.log.status==='late'?'warn':'success'"/></article></div><EmptyState v-else icon="pi pi-history" title="Sin historial" description="Las tomas que registres aparecerán acá."/></template></Card></div>
<Dialog v-model:visible="visible" modal :header="editingId?'Editar medicación':'Nueva medicación'" :style="{width:'min(94vw,46rem)'}"><div class="form-grid"><label class="field"><span>Nombre</span><InputText v-model="form.name" placeholder="Ej. Vitamina D" autofocus/></label><label class="field"><span>Dosis</span><InputText v-model="form.dose" placeholder="Ej. 1 comprimido · 500 mg"/></label><label class="field"><span>Tipo de tratamiento</span><Select v-model="form.treatmentType" :options="[{label:'Continuo',value:'continuous'},{label:'Temporal',value:'temporary'},{label:'Según necesidad',value:'asNeeded'}]" option-label="label" option-value="value"/></label><label class="field"><span>Profesional</span><InputText v-model="form.doctor" placeholder="Opcional"/></label><label class="field"><span>Fecha de inicio</span><InputText v-model="form.startDate" type="date"/></label><label class="field"><span>Fecha de finalización</span><InputText v-model="form.endDate" type="date" :disabled="form.treatmentType!=='temporary'"/></label><label class="field full"><span>Horarios separados por coma</span><InputText v-model="form.timesText" placeholder="08:00, 20:00" :disabled="form.treatmentType==='asNeeded'"/><small>Formato de 24 horas.</small></label><label class="field full"><span>Días</span><MultiSelect v-model="form.days" :options="weekdays" option-label="label" option-value="value" display="chip"/></label><label class="field"><span>Stock actual</span><InputNumber v-model="form.stock" :min="0"/></label><label class="field"><span>Avisar cuando queden</span><InputNumber v-model="form.stockAlert" :min="0"/></label><label class="field"><span>Unidad</span><InputText v-model="form.unit" placeholder="comprimidos, ml, dosis"/></label><div class="field"><span>Color</span><div class="color-picker"><button v-for="color in colors" :key="color" type="button" :style="{background:color}" :class="{selected:form.color===color}" @click="form.color=color"/></div></div><label class="field full"><span>Notas e indicaciones</span><Textarea v-model="form.notes" rows="3" auto-resize/></label><label class="switch-field full"><span><strong>Tratamiento activo</strong><small>Se mostrará en tu agenda y recordatorios.</small></span><ToggleSwitch v-model="form.active"/></label></div><template #footer><Button label="Cancelar" text severity="secondary" @click="visible=false"/><Button label="Guardar medicación" icon="pi pi-check" @click="save"/></template></Dialog>
<Dialog v-model:visible="stockVisible" modal header="Actualizar stock" :style="{width:'min(92vw,28rem)'}"><p class="dialog-copy">{{stockTarget?.name}}</p><label class="field"><span>Cantidad disponible</span><InputNumber v-model="stockValue" :min="0" :suffix="` ${stockTarget?.unit??'unidades'}`" autofocus/></label><template #footer><Button label="Cancelar" text @click="stockVisible=false"/><Button label="Guardar" icon="pi pi-check" @click="saveStock"/></template></Dialog>
</section></template>
