<script setup lang="ts">
import { computed, reactive, ref } from 'vue'
import Button from 'primevue/button'
import Card from 'primevue/card'
import Dialog from 'primevue/dialog'
import InputText from 'primevue/inputtext'
import Select from 'primevue/select'
import Textarea from 'primevue/textarea'
import Tag from 'primevue/tag'
import { useConfirm } from 'primevue/useconfirm'
import { useToast } from 'primevue/usetoast'
import EmptyState from '@/components/EmptyState.vue'
import ModuleTabs from '@/components/ModuleTabs.vue'
import PageHeader from '@/components/PageHeader.vue'
import { useAppStore } from '@/stores/app'
import type { HealthProfessional, MedicalAppointment, MedicalDocument } from '@/types/domain'
import { formatDate, todayKey } from '@/utils/date'
import { createId } from '@/utils/id'
import { healthTabs } from './navigation'

const store=useAppStore();const toast=useToast();const confirm=useConfirm();const section=ref<'appointments'|'professionals'|'documents'>('appointments');const appointmentVisible=ref(false);const professionalVisible=ref(false);const documentVisible=ref(false);const editingId=ref<string|null>(null)
const appointmentForm=reactive({title:'',date:todayKey(),time:'09:00',professionalId:'',center:'',location:'',notes:'',status:'scheduled' as 'scheduled'|'completed'|'cancelled'})
const professionalForm=reactive({name:'',specialty:'',phone:'',email:'',center:'',address:'',notes:''})
const documentForm=reactive({title:'',type:'study' as 'study'|'prescription'|'certificate'|'other',date:todayKey(),professionalId:'',notes:''})
const professionals=computed(()=>store.data.healthProfessionals.map(item=>({label:`${item.name} · ${item.specialty}`,value:item.id})))
const appointments=computed(()=>[...store.data.medicalAppointments].sort((a,b)=>`${b.date}${b.time}`.localeCompare(`${a.date}${a.time}`)))
const upcoming=computed(()=>appointments.value.filter(item=>item.status==='scheduled'&&item.date>=store.today).length)
const professionalName=(id:string)=>store.data.healthProfessionals.find(item=>item.id===id)?.name??'Sin profesional asociado'
function openAppointment(item?:MedicalAppointment){editingId.value=item?.id??null;Object.assign(appointmentForm,item??{title:'',date:todayKey(),time:'09:00',professionalId:'',center:'',location:'',notes:'',status:'scheduled'});appointmentVisible.value=true}
function saveAppointment(){if(!appointmentForm.title.trim()||!appointmentForm.date){toast.add({severity:'warn',summary:'Turno incompleto',detail:'Indicá título y fecha.',life:2600});return}store.upsert('medicalAppointments',{id:editingId.value??createId('appointment'),...appointmentForm,title:appointmentForm.title.trim()});appointmentVisible.value=false;toast.add({severity:'success',summary:'Turno guardado',detail:'También aparecerá en tu resumen de salud.',life:2200})}
function openProfessional(item?:HealthProfessional){editingId.value=item?.id??null;Object.assign(professionalForm,item??{name:'',specialty:'',phone:'',email:'',center:'',address:'',notes:''});professionalVisible.value=true}
function saveProfessional(){if(!professionalForm.name.trim()||!professionalForm.specialty.trim()){toast.add({severity:'warn',summary:'Profesional incompleto',detail:'Indicá nombre y especialidad.',life:2600});return}store.upsert('healthProfessionals',{id:editingId.value??createId('professional'),...professionalForm,name:professionalForm.name.trim(),specialty:professionalForm.specialty.trim()});professionalVisible.value=false}
function openDocument(item?:MedicalDocument){editingId.value=item?.id??null;Object.assign(documentForm,item??{title:'',type:'study',date:todayKey(),professionalId:'',notes:''});documentVisible.value=true}
function saveDocument(){if(!documentForm.title.trim()||!documentForm.date){toast.add({severity:'warn',summary:'Documento incompleto',detail:'Indicá nombre y fecha.',life:2600});return}store.upsert('medicalDocuments',{id:editingId.value??createId('document'),...documentForm,title:documentForm.title.trim()});documentVisible.value=false}
function remove(collection:'medicalAppointments'|'healthProfessionals'|'medicalDocuments',id:string,title:string){confirm.require({message:`¿Eliminar “${title}”?`,header:'Confirmar eliminación',icon:'pi pi-exclamation-triangle',rejectProps:{label:'Cancelar',severity:'secondary',outlined:true},acceptProps:{label:'Eliminar',severity:'danger'},accept:()=>store.remove(collection,id)})}
function complete(item:MedicalAppointment){store.upsert('medicalAppointments',{...item,status:item.status==='completed'?'scheduled':'completed'})}
const statusSeverity=(status:string)=>status==='completed'?'success':status==='cancelled'?'danger':'info'
</script>

<template><section class="page-container"><PageHeader eyebrow="Agenda médica" title="Turnos y documentos" description="Organizá consultas, profesionales, estudios, recetas y certificados."><Button :label="section==='appointments'?'Nuevo turno':section==='professionals'?'Nuevo profesional':'Nuevo documento'" icon="pi pi-plus" @click="section==='appointments'?openAppointment():section==='professionals'?openProfessional():openDocument()"/></PageHeader><ModuleTabs :tabs="healthTabs"/>
<div class="segment-control"><button :class="{active:section==='appointments'}" @click="section='appointments'"><i class="pi pi-calendar-plus"/> Turnos <b>{{upcoming}}</b></button><button :class="{active:section==='professionals'}" @click="section='professionals'"><i class="pi pi-user"/> Profesionales <b>{{store.data.healthProfessionals.length}}</b></button><button :class="{active:section==='documents'}" @click="section='documents'"><i class="pi pi-file"/> Documentos <b>{{store.data.medicalDocuments.length}}</b></button></div>
<div v-if="section==='appointments'"><div v-if="appointments.length" class="appointment-cards"><Card v-for="item in appointments" :key="item.id" class="appointment-card"><template #content><div class="appointment-date"><strong>{{formatDate(item.date,'dd')}}</strong><span>{{formatDate(item.date,'MMM')}}</span><small>{{item.time}}</small></div><div class="appointment-info"><div><Tag :value="item.status==='scheduled'?'Programado':item.status==='completed'?'Completado':'Cancelado'" :severity="statusSeverity(item.status)" rounded/><h3>{{item.title}}</h3><p>{{professionalName(item.professionalId)}}<template v-if="item.center"> · {{item.center}}</template></p></div><div class="entity-meta"><span v-if="item.location"><i class="pi pi-map-marker"/> {{item.location}}</span><span v-if="item.notes"><i class="pi pi-align-left"/> {{item.notes}}</span></div><div class="entity-actions"><Button :label="item.status==='completed'?'Reabrir':'Marcar realizado'" icon="pi pi-check" severity="success" text @click="complete(item)"/><Button label="Editar" icon="pi pi-pencil" text @click="openAppointment(item)"/><Button icon="pi pi-trash" text severity="danger" @click="remove('medicalAppointments',item.id,item.title)"/></div></div></template></Card></div><EmptyState v-else icon="pi pi-calendar-plus" title="No hay turnos cargados" description="Agendá consultas, controles y estudios médicos."/></div>
<div v-else-if="section==='professionals'"><div v-if="store.data.healthProfessionals.length" class="entity-grid"><Card v-for="item in store.data.healthProfessionals" :key="item.id" class="entity-card"><template #content><div class="entity-header"><span class="row-icon blue"><i class="pi pi-user"/></span><div><h3>{{item.name}}</h3><p>{{item.specialty}}</p></div></div><div class="entity-meta"><span v-if="item.center"><i class="pi pi-building"/> {{item.center}}</span><span v-if="item.phone"><i class="pi pi-phone"/> {{item.phone}}</span><span v-if="item.email"><i class="pi pi-envelope"/> {{item.email}}</span><span v-if="item.address"><i class="pi pi-map-marker"/> {{item.address}}</span></div><p v-if="item.notes" class="note">{{item.notes}}</p><div class="entity-actions"><Button label="Editar" icon="pi pi-pencil" text @click="openProfessional(item)"/><Button label="Eliminar" icon="pi pi-trash" text severity="danger" @click="remove('healthProfessionals',item.id,item.name)"/></div></template></Card></div><EmptyState v-else icon="pi pi-user" title="Sin profesionales" description="Guardá especialistas y centros para usarlos en tus turnos."/></div>
<div v-else><div v-if="store.data.medicalDocuments.length" class="document-grid"><Card v-for="item in store.data.medicalDocuments" :key="item.id" class="document-card"><template #content><span class="document-icon"><i :class="item.type==='study'?'pi pi-chart-bar':item.type==='prescription'?'pi pi-file-edit':item.type==='certificate'?'pi pi-verified':'pi pi-file'"/></span><Tag :value="item.type==='study'?'Estudio':item.type==='prescription'?'Receta':item.type==='certificate'?'Certificado':'Otro'" severity="secondary" rounded/><h3>{{item.title}}</h3><p>{{formatDate(item.date,'dd MMMM yyyy')}}</p><small>{{professionalName(item.professionalId)}}</small><p v-if="item.notes" class="note">{{item.notes}}</p><div class="entity-actions"><Button label="Editar" icon="pi pi-pencil" text @click="openDocument(item)"/><Button icon="pi pi-trash" text severity="danger" @click="remove('medicalDocuments',item.id,item.title)"/></div></template></Card></div><EmptyState v-else icon="pi pi-file" title="Sin documentos registrados" description="Catalogá estudios, recetas y certificados. Los archivos se incorporarán con la base de datos."/></div>
<Dialog v-model:visible="appointmentVisible" modal :header="editingId?'Editar turno':'Nuevo turno'" :style="{width:'min(94vw,42rem)'}"><div class="form-grid"><label class="field full"><span>Motivo o título</span><InputText v-model="appointmentForm.title" placeholder="Ej. Control clínico" autofocus/></label><label class="field"><span>Fecha</span><InputText v-model="appointmentForm.date" type="date"/></label><label class="field"><span>Hora</span><InputText v-model="appointmentForm.time" type="time"/></label><label class="field full"><span>Profesional</span><Select v-model="appointmentForm.professionalId" :options="professionals" option-label="label" option-value="value" placeholder="Sin profesional asociado" show-clear/></label><label class="field"><span>Centro médico</span><InputText v-model="appointmentForm.center"/></label><label class="field"><span>Dirección</span><InputText v-model="appointmentForm.location"/></label><label class="field full"><span>Notas y preparación</span><Textarea v-model="appointmentForm.notes" rows="3" auto-resize/></label><label class="field full"><span>Estado</span><Select v-model="appointmentForm.status" :options="[{label:'Programado',value:'scheduled'},{label:'Completado',value:'completed'},{label:'Cancelado',value:'cancelled'}]" option-label="label" option-value="value"/></label></div><template #footer><Button label="Cancelar" text @click="appointmentVisible=false"/><Button label="Guardar turno" icon="pi pi-check" @click="saveAppointment"/></template></Dialog>
<Dialog v-model:visible="professionalVisible" modal :header="editingId?'Editar profesional':'Nuevo profesional'" :style="{width:'min(94vw,42rem)'}"><div class="form-grid"><label class="field"><span>Nombre</span><InputText v-model="professionalForm.name" autofocus/></label><label class="field"><span>Especialidad</span><InputText v-model="professionalForm.specialty"/></label><label class="field"><span>Teléfono</span><InputText v-model="professionalForm.phone"/></label><label class="field"><span>Correo</span><InputText v-model="professionalForm.email" type="email"/></label><label class="field"><span>Centro</span><InputText v-model="professionalForm.center"/></label><label class="field"><span>Dirección</span><InputText v-model="professionalForm.address"/></label><label class="field full"><span>Notas</span><Textarea v-model="professionalForm.notes" rows="3"/></label></div><template #footer><Button label="Cancelar" text @click="professionalVisible=false"/><Button label="Guardar" icon="pi pi-check" @click="saveProfessional"/></template></Dialog>
<Dialog v-model:visible="documentVisible" modal :header="editingId?'Editar documento':'Nuevo documento'" :style="{width:'min(94vw,38rem)'}"><div class="form-grid"><label class="field full"><span>Título</span><InputText v-model="documentForm.title" autofocus/></label><label class="field"><span>Tipo</span><Select v-model="documentForm.type" :options="[{label:'Estudio',value:'study'},{label:'Receta',value:'prescription'},{label:'Certificado',value:'certificate'},{label:'Otro',value:'other'}]" option-label="label" option-value="value"/></label><label class="field"><span>Fecha</span><InputText v-model="documentForm.date" type="date"/></label><label class="field full"><span>Profesional</span><Select v-model="documentForm.professionalId" :options="professionals" option-label="label" option-value="value" show-clear/></label><label class="field full"><span>Notas o resultado</span><Textarea v-model="documentForm.notes" rows="4" auto-resize/></label></div><template #footer><Button label="Cancelar" text @click="documentVisible=false"/><Button label="Guardar" icon="pi pi-check" @click="saveDocument"/></template></Dialog>
</section></template>
