<script setup lang="ts">
import { computed, reactive, ref } from 'vue'
import Button from 'primevue/button'
import Card from 'primevue/card'
import Dialog from 'primevue/dialog'
import InputNumber from 'primevue/inputnumber'
import InputText from 'primevue/inputtext'
import MultiSelect from 'primevue/multiselect'
import Select from 'primevue/select'
import Textarea from 'primevue/textarea'
import Tag from 'primevue/tag'
import { useConfirm } from 'primevue/useconfirm'
import { useToast } from 'primevue/usetoast'
import EmptyState from '@/components/EmptyState.vue'
import ModuleTabs from '@/components/ModuleTabs.vue'
import PageHeader from '@/components/PageHeader.vue'
import { useAppStore } from '@/stores/app'
import type { EmergencyContact, SymptomLog, VitalRecord } from '@/types/domain'
import { formatDate, todayKey } from '@/utils/date'
import { createId } from '@/utils/id'
import { healthTabs } from './navigation'

const store=useAppStore();const toast=useToast();const confirm=useConfirm();const section=ref<'vitals'|'symptoms'|'emergency'>('vitals');const vitalVisible=ref(false);const symptomVisible=ref(false);const contactVisible=ref(false);const editingId=ref<string|null>(null)
const vitalTypes=[{label:'Peso',value:'weight',unit:'kg'},{label:'Presión arterial',value:'pressure',unit:'mmHg'},{label:'Temperatura',value:'temperature',unit:'°C'},{label:'Glucosa',value:'glucose',unit:'mg/dL'},{label:'Frecuencia cardíaca',value:'heartRate',unit:'lpm'},{label:'Sueño',value:'sleep',unit:'horas'}]
const vitalForm=reactive({type:'weight' as VitalRecord['type'],value:'',unit:'kg',date:todayKey(),time:new Date().toTimeString().slice(0,5),notes:''})
const symptomForm=reactive({symptom:'',intensity:5,date:todayKey(),time:new Date().toTimeString().slice(0,5),notes:'',medicationIds:[] as string[]})
const contactForm=reactive({name:'',relation:'',phone:'',notes:''})
const medicationOptions=computed(()=>store.data.medications.map(item=>({label:item.name,value:item.id})))
const vitals=computed(()=>[...store.data.vitalRecords].sort((a,b)=>`${b.date}${b.time}`.localeCompare(`${a.date}${a.time}`)));const symptoms=computed(()=>[...store.data.symptomLogs].sort((a,b)=>`${b.date}${b.time}`.localeCompare(`${a.date}${a.time}`)))
const latestByType=computed(()=>{const map=new Map<string,VitalRecord>();vitals.value.forEach(item=>{if(!map.has(item.type))map.set(item.type,item)});return [...map.values()]})
const typeLabel=(type:string)=>vitalTypes.find(item=>item.value===type)?.label??type
function changeVitalType(type:VitalRecord['type']){vitalForm.type=type;vitalForm.unit=vitalTypes.find(item=>item.value===type)?.unit??''}
function openVital(item?:VitalRecord){editingId.value=item?.id??null;Object.assign(vitalForm,item??{type:'weight',value:'',unit:'kg',date:todayKey(),time:new Date().toTimeString().slice(0,5),notes:''});vitalVisible.value=true}
function saveVital(){if(!vitalForm.value.trim()){toast.add({severity:'warn',summary:'Medición incompleta',detail:'Indicá el valor registrado.',life:2500});return}store.upsert('vitalRecords',{id:editingId.value??createId('vital'),...vitalForm});vitalVisible.value=false;toast.add({severity:'success',summary:'Medición guardada',detail:'Se agregó a tu historial.',life:2200})}
function openSymptom(item?:SymptomLog){editingId.value=item?.id??null;Object.assign(symptomForm,item??{symptom:'',intensity:5,date:todayKey(),time:new Date().toTimeString().slice(0,5),notes:'',medicationIds:[]});symptomVisible.value=true}
function saveSymptom(){if(!symptomForm.symptom.trim()){toast.add({severity:'warn',summary:'Registro incompleto',detail:'Indicá el síntoma u observación.',life:2500});return}store.upsert('symptomLogs',{id:editingId.value??createId('symptom'),...symptomForm,symptom:symptomForm.symptom.trim(),medicationIds:[...symptomForm.medicationIds]});symptomVisible.value=false}
function openContact(item?:EmergencyContact){editingId.value=item?.id??null;Object.assign(contactForm,item??{name:'',relation:'',phone:'',notes:''});contactVisible.value=true}
function saveContact(){if(!contactForm.name.trim()||!contactForm.phone.trim()){toast.add({severity:'warn',summary:'Contacto incompleto',detail:'Indicá nombre y teléfono.',life:2500});return}store.upsert('emergencyContacts',{id:editingId.value??createId('contact'),...contactForm,name:contactForm.name.trim()});contactVisible.value=false}
function remove(collection:'vitalRecords'|'symptomLogs'|'emergencyContacts',id:string,title:string){confirm.require({message:`¿Eliminar “${title}”?`,header:'Confirmar eliminación',icon:'pi pi-exclamation-triangle',rejectProps:{label:'Cancelar',severity:'secondary',outlined:true},acceptProps:{label:'Eliminar',severity:'danger'},accept:()=>store.remove(collection,id)})}
</script>

<template><section class="page-container"><PageHeader eyebrow="Registro personal" title="Seguimiento de salud" description="Guardá mediciones, síntomas y contactos importantes para tener contexto a lo largo del tiempo."><Button :label="section==='vitals'?'Nueva medición':section==='symptoms'?'Registrar síntoma':'Nuevo contacto'" icon="pi pi-plus" @click="section==='vitals'?openVital():section==='symptoms'?openSymptom():openContact()"/></PageHeader><ModuleTabs :tabs="healthTabs"/>
<div class="segment-control"><button :class="{active:section==='vitals'}" @click="section='vitals'"><i class="pi pi-chart-line"/> Mediciones <b>{{store.data.vitalRecords.length}}</b></button><button :class="{active:section==='symptoms'}" @click="section='symptoms'"><i class="pi pi-heart"/> Síntomas <b>{{store.data.symptomLogs.length}}</b></button><button :class="{active:section==='emergency'}" @click="section='emergency'"><i class="pi pi-phone"/> Emergencia <b>{{store.data.emergencyContacts.length}}</b></button></div>
<div v-if="section==='vitals'"><div v-if="latestByType.length" class="vital-summary"><article v-for="item in latestByType" :key="item.type"><span><i class="pi pi-chart-line"/></span><small>{{typeLabel(item.type)}}</small><strong>{{item.value}} {{item.unit}}</strong><p>{{formatDate(item.date,'dd MMM yyyy')}}</p></article></div><Card class="content-card"><template #title><div class="card-title"><span>Historial de mediciones</span><Button label="Agregar" icon="pi pi-plus" size="small" text @click="openVital()"/></div></template><template #content><div v-if="vitals.length" class="record-table"><article v-for="item in vitals" :key="item.id"><span class="row-icon blue"><i class="pi pi-chart-line"/></span><div><strong>{{typeLabel(item.type)}}</strong><small>{{formatDate(item.date,'dd/MM/yyyy')}} · {{item.time}}</small></div><b>{{item.value}} {{item.unit}}</b><p>{{item.notes}}</p><span><Button icon="pi pi-pencil" text rounded @click="openVital(item)"/><Button icon="pi pi-trash" text rounded severity="danger" @click="remove('vitalRecords',item.id,typeLabel(item.type))"/></span></article></div><EmptyState v-else icon="pi pi-chart-line" title="Sin mediciones" description="Registrá peso, presión, temperatura, glucosa, pulso o sueño."/></template></Card></div>
<div v-else-if="section==='symptoms'"><div v-if="symptoms.length" class="symptom-list"><Card v-for="item in symptoms" :key="item.id" class="symptom-card"><template #content><div class="symptom-top"><span :class="`intensity intensity-${Math.ceil(item.intensity/2)}`">{{item.intensity}}/10</span><div><h3>{{item.symptom}}</h3><p>{{formatDate(item.date,'dd MMMM yyyy')}} · {{item.time}}</p></div><Tag :value="item.intensity>=8?'Intenso':item.intensity>=5?'Moderado':'Leve'" :severity="item.intensity>=8?'danger':item.intensity>=5?'warn':'success'"/></div><p v-if="item.notes" class="note">{{item.notes}}</p><div v-if="item.medicationIds.length" class="chip-list"><span v-for="id in item.medicationIds" :key="id">{{store.data.medications.find(x=>x.id===id)?.name??'Medicación'}}</span></div><div class="entity-actions"><Button label="Editar" icon="pi pi-pencil" text @click="openSymptom(item)"/><Button label="Eliminar" icon="pi pi-trash" text severity="danger" @click="remove('symptomLogs',item.id,item.symptom)"/></div></template></Card></div><EmptyState v-else icon="pi pi-heart" title="Sin síntomas registrados" description="Guardá una observación cuando necesites recordar evolución, intensidad o contexto."/></div>
<div v-else><div class="emergency-banner"><span><i class="pi pi-shield"/></span><div><h2>Información rápida para una urgencia</h2><p>Guardá personas de confianza. Esta sección no reemplaza los números oficiales de emergencia.</p></div></div><div v-if="store.data.emergencyContacts.length" class="entity-grid"><Card v-for="item in store.data.emergencyContacts" :key="item.id" class="entity-card"><template #content><div class="entity-header"><span class="row-icon rose"><i class="pi pi-phone"/></span><div><h3>{{item.name}}</h3><p>{{item.relation}}</p></div></div><a :href="`tel:${item.phone}`" class="contact-phone"><i class="pi pi-phone"/> {{item.phone}}</a><p v-if="item.notes" class="note">{{item.notes}}</p><div class="entity-actions"><Button label="Editar" icon="pi pi-pencil" text @click="openContact(item)"/><Button label="Eliminar" icon="pi pi-trash" text severity="danger" @click="remove('emergencyContacts',item.id,item.name)"/></div></template></Card></div><EmptyState v-else icon="pi pi-phone" title="No hay contactos de emergencia" description="Agregá familiares o personas de confianza con su teléfono."/></div>
<Dialog v-model:visible="vitalVisible" modal :header="editingId?'Editar medición':'Nueva medición'" :style="{width:'min(92vw,36rem)'}"><div class="form-grid"><label class="field full"><span>Tipo</span><Select :model-value="vitalForm.type" :options="vitalTypes" option-label="label" option-value="value" @update:model-value="changeVitalType"/></label><label class="field"><span>Valor</span><InputText v-model="vitalForm.value" placeholder="Ej. 120/80" autofocus/></label><label class="field"><span>Unidad</span><InputText v-model="vitalForm.unit"/></label><label class="field"><span>Fecha</span><InputText v-model="vitalForm.date" type="date"/></label><label class="field"><span>Hora</span><InputText v-model="vitalForm.time" type="time"/></label><label class="field full"><span>Notas</span><Textarea v-model="vitalForm.notes" rows="3"/></label></div><template #footer><Button label="Cancelar" text @click="vitalVisible=false"/><Button label="Guardar" icon="pi pi-check" @click="saveVital"/></template></Dialog>
<Dialog v-model:visible="symptomVisible" modal :header="editingId?'Editar registro':'Registrar síntoma'" :style="{width:'min(92vw,40rem)'}"><div class="form-grid"><label class="field full"><span>Síntoma u observación</span><InputText v-model="symptomForm.symptom" placeholder="Ej. Dolor de cabeza, mareo, cansancio" autofocus/></label><label class="field"><span>Intensidad</span><InputNumber v-model="symptomForm.intensity" suffix=" / 10" :min="1" :max="10"/></label><label class="field"><span>Fecha</span><InputText v-model="symptomForm.date" type="date"/></label><label class="field"><span>Hora</span><InputText v-model="symptomForm.time" type="time"/></label><label class="field full"><span>Medicaciones relacionadas</span><MultiSelect v-model="symptomForm.medicationIds" :options="medicationOptions" option-label="label" option-value="value" display="chip"/></label><label class="field full"><span>Contexto y notas</span><Textarea v-model="symptomForm.notes" rows="4" auto-resize/></label></div><template #footer><Button label="Cancelar" text @click="symptomVisible=false"/><Button label="Guardar" icon="pi pi-check" @click="saveSymptom"/></template></Dialog>
<Dialog v-model:visible="contactVisible" modal :header="editingId?'Editar contacto':'Nuevo contacto de emergencia'" :style="{width:'min(92vw,34rem)'}"><div class="form-grid"><label class="field"><span>Nombre</span><InputText v-model="contactForm.name" autofocus/></label><label class="field"><span>Relación</span><InputText v-model="contactForm.relation" placeholder="Ej. Pareja, familiar"/></label><label class="field full"><span>Teléfono</span><InputText v-model="contactForm.phone" type="tel"/></label><label class="field full"><span>Notas</span><Textarea v-model="contactForm.notes" rows="3"/></label></div><template #footer><Button label="Cancelar" text @click="contactVisible=false"/><Button label="Guardar" icon="pi pi-check" @click="saveContact"/></template></Dialog>
</section></template>
