<script setup lang="ts">
import { ref } from 'vue'
import Button from 'primevue/button'
import Card from 'primevue/card'
import InputText from 'primevue/inputtext'
import Select from 'primevue/select'
import ToggleSwitch from 'primevue/toggleswitch'
import Message from 'primevue/message'
import { useConfirm } from 'primevue/useconfirm'
import { useToast } from 'primevue/usetoast'
import PageHeader from '@/components/PageHeader.vue'
import { useAppStore } from '@/stores/app'

const store=useAppStore();const toast=useToast();const confirm=useConfirm();const fileInput=ref<HTMLInputElement|null>(null)
const currencies=[{label:'Peso argentino (ARS)',value:'ARS'},{label:'Dólar estadounidense (USD)',value:'USD'},{label:'Euro (EUR)',value:'EUR'}]
const modules=[{icon:'pi pi-calendar',title:'Calendario avanzado',description:'Mes, semana, día, agenda y eventos recurrentes.',status:'Completo'},{icon:'pi pi-wallet',title:'Finanzas',description:'Movimientos, presupuestos, compromisos, deudas y ahorro.',status:'Completo'},{icon:'pi pi-heart',title:'Salud',description:'Medicación, stock, turnos, profesionales y seguimiento.',status:'Completo'},{icon:'pi pi-check-square',title:'Tareas y enfoque',description:'Subtareas, prioridades, recurrencia y temporizador.',status:'Completo'},{icon:'pi pi-home',title:'Hogar',description:'Compras, inventario, mantenimiento y garantías.',status:'Completo'},{icon:'pi pi-cloud',title:'Base de datos y cuentas',description:'Sincronización multidispositivo y archivos privados.',status:'Próxima etapa'}]
async function showTestNotification(){const options:NotificationOptions={body:'Los recordatorios de medicación, tareas y eventos están activos mientras la aplicación permanezca abierta.',icon:`${import.meta.env.BASE_URL}pwa-icon.svg`};if('serviceWorker'in navigator){const registration=await navigator.serviceWorker.getRegistration();if(registration){await registration.showNotification('Vida Organizada',options);return}}new Notification('Vida Organizada',options)}
async function notifications(enabled:boolean){if(!enabled){store.data.settings.notificationsEnabled=false;return}if(!('Notification'in window)){store.data.settings.notificationsEnabled=false;toast.add({severity:'warn',summary:'No disponible',detail:'Este navegador no soporta notificaciones.',life:3500});return}const permission=await Notification.requestPermission();store.data.settings.notificationsEnabled=permission==='granted';if(permission==='granted'){try{await showTestNotification()}catch{toast.add({severity:'warn',summary:'Permiso concedido',detail:'No se pudo mostrar la prueba.',life:3000})}}else toast.add({severity:'warn',summary:'Permiso no concedido',detail:'Podés habilitarlo desde el navegador.',life:3000})}
async function importFile(event:Event){const file=(event.target as HTMLInputElement).files?.[0];if(!file)return;try{await store.importData(file);toast.add({severity:'success',summary:'Respaldo restaurado',detail:'Todos los módulos fueron importados.',life:2800})}catch{toast.add({severity:'error',summary:'Archivo inválido',detail:'No es un respaldo válido de Vida Organizada.',life:3500})}finally{if(fileInput.value)fileInput.value.value=''}}
function reset(){confirm.require({message:'Se borrarán todos los datos de todos los módulos guardados en este dispositivo.',header:'Restablecer aplicación',icon:'pi pi-exclamation-triangle',rejectProps:{label:'Cancelar',severity:'secondary',outlined:true},acceptProps:{label:'Borrar todo',severity:'danger'},accept:()=>store.resetData()})}
</script>

<template><section class="page-container"><PageHeader eyebrow="Preferencias y privacidad" title="Configuración" description="Personalizá la experiencia, administrá recordatorios y protegé tu información."/>
<div class="settings-grid"><Card class="content-card"><template #title>Perfil y apariencia</template><template #content><div class="settings-form"><label class="field"><span>Nombre para mostrar</span><InputText v-model="store.data.settings.displayName"/></label><label class="field"><span>Moneda principal</span><Select v-model="store.data.settings.currency" :options="currencies" option-label="label" option-value="value"/></label><label class="switch-field"><span><strong>Modo oscuro</strong><small>Adapta todas las pantallas y componentes.</small></span><ToggleSwitch v-model="store.data.settings.darkMode"/></label><label class="switch-field"><span><strong>Recordatorios locales</strong><small>Medicación, tareas y eventos mientras la aplicación está abierta. Con la app cerrada requerirán push y backend.</small></span><ToggleSwitch :model-value="store.data.settings.notificationsEnabled" @update:model-value="notifications"/></label></div></template></Card>
<Card class="content-card"><template #title>Datos y respaldo</template><template #content><Message severity="info" :closable="false">Hasta conectar la base de datos, toda la información permanece en este navegador. Exportá un respaldo antes de cambiar de equipo o borrar datos.</Message><div class="data-actions"><Button label="Exportar respaldo completo" icon="pi pi-download" severity="secondary" @click="store.exportData"/><Button label="Importar respaldo" icon="pi pi-upload" severity="secondary" outlined @click="fileInput?.click()"/><input ref="fileInput" class="sr-only" type="file" accept="application/json" @change="importFile"/><Button label="Borrar todos los datos" icon="pi pi-trash" severity="danger" text @click="reset"/></div></template></Card></div>
<Card class="content-card"><template #title>Estado de la aplicación</template><template #content><div class="roadmap-grid"><article v-for="item in modules" :key="item.title"><span><i :class="item.icon"/></span><div><strong>{{item.title}}</strong><p>{{item.description}}</p><small :class="item.status==='Completo'?'income':''">{{item.status}}</small></div></article></div></template></Card>
</section></template>
