<script setup lang="ts">
import { computed, reactive, ref } from 'vue'
import { addDays, addMonths, addWeeks, eachDayOfInterval, endOfMonth, endOfWeek, format, isSameDay, parseISO, startOfDay, startOfMonth, startOfWeek, subDays, subMonths, subWeeks } from 'date-fns'
import { es } from 'date-fns/locale'
import Button from 'primevue/button'
import Card from 'primevue/card'
import Dialog from 'primevue/dialog'
import InputText from 'primevue/inputtext'
import MultiSelect from 'primevue/multiselect'
import Select from 'primevue/select'
import Textarea from 'primevue/textarea'
import ToggleSwitch from 'primevue/toggleswitch'
import Tag from 'primevue/tag'
import { useConfirm } from 'primevue/useconfirm'
import { useToast } from 'primevue/usetoast'
import EmptyState from '@/components/EmptyState.vue'
import PageHeader from '@/components/PageHeader.vue'
import { useAppStore } from '@/stores/app'
import type { CalendarEvent, EventKind, Recurrence } from '@/types/domain'
import { formatDate } from '@/utils/date'
import { createId } from '@/utils/id'

interface Occurrence extends CalendarEvent { occurrenceDate: string }
const store=useAppStore();const toast=useToast();const confirm=useConfirm()
const view=ref<'month'|'week'|'day'|'agenda'>('month');const cursor=ref(startOfDay(new Date()));const selected=ref(startOfDay(new Date()));const visible=ref(false);const editingId=ref<string|null>(null);const draggedId=ref<string|null>(null);const search=ref('');const calendarFilter=ref('Todos')
const kinds=[{label:'Personal',value:'personal'},{label:'Turno',value:'appointment'},{label:'Tarea',value:'task'}];const colors:Record<EventKind,string>={personal:'#8b5cf6',appointment:'#0ea5e9',task:'#f59e0b'};const calendars=['Personal','Salud','Trabajo','Estudio','Hogar'];const reminders=[{label:'A la hora',value:0},{label:'5 minutos antes',value:5},{label:'15 minutos antes',value:15},{label:'30 minutos antes',value:30},{label:'1 hora antes',value:60},{label:'1 día antes',value:1440}]
const form=reactive({title:'',date:format(new Date(),'yyyy-MM-dd'),time:'09:00',endTime:'10:00',allDay:false,kind:'personal' as EventKind,notes:'',color:colors.personal,completed:false,recurrence:'none' as Recurrence,recurrenceUntil:'',reminderMinutes:[30] as number[],location:'',link:'',participantsText:'',calendarId:'Personal'})
const monthStart=computed(()=>startOfMonth(cursor.value));const monthDays=computed(()=>eachDayOfInterval({start:startOfWeek(monthStart.value,{weekStartsOn:1}),end:endOfWeek(endOfMonth(monthStart.value),{weekStartsOn:1})}));const weekStart=computed(()=>startOfWeek(cursor.value,{weekStartsOn:1}));const weekDays=computed(()=>eachDayOfInterval({start:weekStart.value,end:addDays(weekStart.value,6)}))
function nextDate(date:Date,recurrence:Recurrence){if(recurrence==='daily')return addDays(date,1);if(recurrence==='weekly')return addWeeks(date,1);if(recurrence==='monthly')return addMonths(date,1);if(recurrence==='yearly')return addMonths(date,12);return addDays(date,10000)}
function occurrencesOf(event:CalendarEvent,start:Date,end:Date){const output:Occurrence[]=[];let date=parseISO(event.date);const recurrence=event.recurrence??'none';const until=event.recurrenceUntil?parseISO(event.recurrenceUntil):end;let guard=0;while(date<=end&&date<=until&&guard<500){if(date>=start)output.push({...event,occurrenceDate:format(date,'yyyy-MM-dd')});if(recurrence==='none')break;date=nextDate(date,recurrence);guard++}return output}
const range=computed(()=>view.value==='month'?[monthDays.value[0],monthDays.value.at(-1)!]:view.value==='week'?[weekDays.value[0],weekDays.value[6]]:view.value==='day'?[cursor.value,cursor.value]:[new Date(),addMonths(new Date(),12)])
const occurrences=computed(()=>store.data.calendarEvents.flatMap(event=>occurrencesOf(event,range.value[0],range.value[1])).filter(item=>calendarFilter.value==='Todos'||(item.calendarId??'Personal')===calendarFilter.value).filter(item=>`${item.title} ${item.notes} ${item.location}`.toLowerCase().includes(search.value.toLowerCase())).sort((a,b)=>`${a.occurrenceDate}${a.allDay?'00:00':a.time}`.localeCompare(`${b.occurrenceDate}${b.allDay?'00:00':b.time}`)))
const forDay=(day:Date)=>occurrences.value.filter(item=>item.occurrenceDate===format(day,'yyyy-MM-dd'));const selectedEvents=computed(()=>forDay(selected.value));const selectedMedications=computed(()=>store.data.medications.filter(item=>item.active&&item.days.includes(selected.value.getDay())).flatMap(item=>item.times.map(time=>({id:`${item.id}-${time}`,time,title:item.name,subtitle:item.dose,color:item.color,type:'Medicación'}))));const selectedRoutines=computed(()=>store.data.routines.filter(item=>item.active&&item.days.includes(selected.value.getDay())).map(item=>({id:item.id,time:item.startTime,title:item.title,subtitle:`${item.durationMinutes} min`,color:item.color,type:'Rutina'})))
const dayAgenda=computed(()=>[...selectedEvents.value.map(item=>({id:item.id,time:item.allDay?'':item.time,title:item.title,subtitle:item.calendarId??'Personal',color:item.color,type:item.kind==='appointment'?'Turno':item.kind==='task'?'Tarea':'Personal',event:item})),...selectedMedications.value,...selectedRoutines.value].sort((a,b)=>a.time.localeCompare(b.time)));const agenda=computed(()=>occurrences.value.filter(item=>item.occurrenceDate>=store.today).slice(0,150));const agendaDates=computed(()=>[...new Set(agenda.value.map(item=>item.occurrenceDate))]);const calendarCounts=computed(()=>calendars.map(label=>({label,count:store.data.calendarEvents.filter(item=>(item.calendarId??'Personal')===label).length})))
const title=computed(()=>view.value==='month'?format(cursor.value,'MMMM yyyy',{locale:es}):view.value==='week'?`${format(weekDays.value[0],'d MMM',{locale:es})} – ${format(weekDays.value[6],'d MMM yyyy',{locale:es})}`:view.value==='day'?format(cursor.value,"EEEE d 'de' MMMM",{locale:es}):'Próximos eventos')
function reset(date=format(selected.value,'yyyy-MM-dd')){editingId.value=null;Object.assign(form,{title:'',date,time:'09:00',endTime:'10:00',allDay:false,kind:'personal',notes:'',color:colors.personal,completed:false,recurrence:'none',recurrenceUntil:'',reminderMinutes:[30],location:'',link:'',participantsText:'',calendarId:'Personal'})}
function create(date=format(selected.value,'yyyy-MM-dd')){reset(date);visible.value=true}
function edit(item:CalendarEvent){editingId.value=item.id;Object.assign(form,{...item,endTime:item.endTime??'',allDay:item.allDay??false,recurrence:item.recurrence??'none',recurrenceUntil:item.recurrenceUntil??'',reminderMinutes:item.reminderMinutes??[],location:item.location??'',link:item.link??'',participantsText:(item.participants??[]).join(', '),calendarId:item.calendarId??'Personal'});visible.value=true}
function save(){if(!form.title.trim()||!form.date){toast.add({severity:'warn',summary:'Evento incompleto',detail:'Indicá título y fecha.',life:2700});return}store.upsertCalendarEvent({id:editingId.value??createId('event'),title:form.title.trim(),date:form.date,time:form.allDay?'':form.time,endTime:form.allDay?'':form.endTime,allDay:form.allDay,kind:form.kind,notes:form.notes.trim(),color:form.color,completed:form.completed,recurrence:form.recurrence,recurrenceUntil:form.recurrence==='none'?'':form.recurrenceUntil,reminderMinutes:[...form.reminderMinutes],location:form.location.trim(),link:form.link.trim(),participants:form.participantsText.split(',').map(value=>value.trim()).filter(Boolean),calendarId:form.calendarId});cursor.value=parseISO(form.date);selected.value=parseISO(form.date);visible.value=false;toast.add({severity:'success',summary:'Evento guardado',detail:'La agenda quedó actualizada.',life:2200})}
function remove(item:CalendarEvent){confirm.require({message:`¿Eliminar “${item.title}”${item.recurrence&&item.recurrence!=='none'?' y toda la serie':''}?`,header:'Eliminar evento',icon:'pi pi-exclamation-triangle',rejectProps:{label:'Cancelar',severity:'secondary',outlined:true},acceptProps:{label:'Eliminar',severity:'danger'},accept:()=>store.removeCalendarEvent(item.id)})}
function navigate(direction:number){if(view.value==='month')cursor.value=direction>0?addMonths(cursor.value,1):subMonths(cursor.value,1);else if(view.value==='week')cursor.value=direction>0?addWeeks(cursor.value,1):subWeeks(cursor.value,1);else cursor.value=direction>0?addDays(cursor.value,1):subDays(cursor.value,1);selected.value=cursor.value}
function goToday(){cursor.value=startOfDay(new Date());selected.value=startOfDay(new Date())}function selectDay(day:Date){selected.value=day;cursor.value=day}function dropOn(day:Date){const item=store.data.calendarEvents.find(event=>event.id===draggedId.value);if(item)store.upsertCalendarEvent({...item,date:format(day,'yyyy-MM-dd')});draggedId.value=null}function changeKind(kind:EventKind){form.kind=kind;form.color=colors[kind]}function removeEditing(){const item=store.data.calendarEvents.find(event=>event.id===editingId.value);if(item){visible.value=false;remove(item)}}
</script>

<template><section class="page-container calendar-page"><PageHeader eyebrow="Agenda unificada" title="Calendario" description="Eventos, tareas, turnos, medicación y rutinas en vistas mensual, semanal, diaria y agenda."><Button label="Nuevo evento" icon="pi pi-plus" @click="create()"/></PageHeader>
<div class="calendar-command"><div class="calendar-nav"><Button icon="pi pi-chevron-left" text rounded @click="navigate(-1)"/><Button label="Hoy" severity="secondary" outlined @click="goToday"/><Button icon="pi pi-chevron-right" text rounded @click="navigate(1)"/><strong>{{title}}</strong></div><div class="calendar-tools"><span class="search-box"><i class="pi pi-search"/><InputText v-model="search" placeholder="Buscar evento..."/></span><div class="view-switch"><button v-for="option in [{v:'month',l:'Mes',i:'pi pi-calendar'},{v:'week',l:'Semana',i:'pi pi-table'},{v:'day',l:'Día',i:'pi pi-list'},{v:'agenda',l:'Agenda',i:'pi pi-bars'}]" :key="option.v" :class="{active:view===option.v}" @click="view=option.v as typeof view"><i :class="option.i"/><span>{{option.l}}</span></button></div></div></div>
<div class="calendar-workspace"><aside class="calendar-side"><Card class="content-card"><template #title>Mis calendarios</template><template #content><button class="calendar-filter" :class="{active:calendarFilter==='Todos'}" @click="calendarFilter='Todos'"><i class="all"/><span>Todos</span><b>{{store.data.calendarEvents.length}}</b></button><button v-for="item in calendarCounts" :key="item.label" class="calendar-filter" :class="{active:calendarFilter===item.label}" @click="calendarFilter=item.label"><i :class="item.label.toLowerCase()"/><span>{{item.label}}</span><b>{{item.count}}</b></button></template></Card><Card class="content-card"><template #title>{{format(selected,"EEEE d 'de' MMMM",{locale:es})}}</template><template #content><div v-if="dayAgenda.length" class="side-agenda"><article v-for="item in dayAgenda" :key="`${item.type}-${item.id}`"><b>{{item.time||'Todo el día'}}</b><i :style="{background:item.color}"/><div><strong>{{item.title}}</strong><small>{{item.type}} · {{item.subtitle}}</small></div></article></div><EmptyState v-else icon="pi pi-calendar" title="Día libre" description="No hay actividades para esta fecha."/><Button label="Agregar en este día" icon="pi pi-plus" text fluid @click="create(format(selected,'yyyy-MM-dd'))"/></template></Card></aside>
<main class="calendar-main"><Card v-if="view==='month'" class="calendar-surface"><template #content><div class="calendar-labels"><span v-for="label in ['Lun','Mar','Mié','Jue','Vie','Sáb','Dom']" :key="label">{{label}}</span></div><div class="advanced-month"><button v-for="day in monthDays" :key="day.toISOString()" :class="['advanced-day',{muted:day.getMonth()!==monthStart.getMonth(),selected:isSameDay(day,selected),today:isSameDay(day,new Date())}]" @click="selectDay(day)" @dblclick="create(format(day,'yyyy-MM-dd'))" @dragover.prevent @drop="dropOn(day)"><span class="day-number">{{format(day,'d')}}</span><div class="day-events"><article v-for="event in forDay(day).slice(0,4)" :key="`${event.id}-${event.occurrenceDate}`" draggable="true" :style="{borderColor:event.color}" @dragstart.stop="draggedId=event.id" @click.stop="edit(event)"><i :style="{background:event.color}"/><b>{{event.allDay?'':event.time}}</b><span>{{event.title}}</span><i v-if="event.recurrence&&event.recurrence!=='none'" class="pi pi-refresh"/></article><small v-if="forDay(day).length>4">+{{forDay(day).length-4}} más</small></div><div class="activity-markers"><i v-if="store.data.medications.some(item=>item.active&&item.days.includes(day.getDay()))" class="marker medication"/><i v-if="store.data.routines.some(item=>item.active&&item.days.includes(day.getDay()))" class="marker routine"/></div></button></div></template></Card>
<Card v-else-if="view==='week'" class="calendar-surface"><template #content><div class="week-header"><span class="time-gutter"/><button v-for="day in weekDays" :key="day.toISOString()" :class="{today:isSameDay(day,new Date()),selected:isSameDay(day,selected)}" @click="selectDay(day)"><small>{{format(day,'EEE',{locale:es})}}</small><strong>{{format(day,'d')}}</strong></button></div><div class="week-grid"><div class="time-column"><span v-for="hour in 24" :key="hour">{{String(hour-1).padStart(2,'0')}}:00</span></div><div v-for="day in weekDays" :key="day.toISOString()" class="week-column" @dragover.prevent @drop="dropOn(day)"><div v-for="hour in 24" :key="hour" class="hour-line" @dblclick="create(format(day,'yyyy-MM-dd'))"/><article v-for="event in forDay(day)" :key="`${event.id}-${event.occurrenceDate}`" draggable="true" class="week-event" :class="{allDay:event.allDay}" :style="event.allDay?{background:event.color}:{top:`${((Number(event.time.slice(0,2))*60+Number(event.time.slice(3)))/1440)*100}%`,height:`${Math.max(3,(((Number((event.endTime||event.time).slice(0,2))*60+Number((event.endTime||event.time).slice(3)))-(Number(event.time.slice(0,2))*60+Number(event.time.slice(3))))/1440)*100)}%`,background:event.color}" @dragstart="draggedId=event.id" @click="edit(event)"><strong>{{event.title}}</strong><small>{{event.allDay?'Todo el día':event.time}}</small></article></div></div></template></Card>
<Card v-else-if="view==='day'" class="calendar-surface day-surface"><template #content><div class="day-top"><div><span class="eyebrow">{{format(cursor,'EEEE',{locale:es})}}</span><strong>{{format(cursor,'d')}}</strong><small>{{format(cursor,'MMMM yyyy',{locale:es})}}</small></div><div class="day-summary"><span><i class="pi pi-calendar"/> {{selectedEvents.length}} eventos</span><span><i class="pi pi-heart"/> {{selectedMedications.length}} tomas</span><span><i class="pi pi-list-check"/> {{selectedRoutines.length}} rutinas</span></div></div><div class="day-timeline"><div v-for="hour in 24" :key="hour" class="day-hour"><b>{{String(hour-1).padStart(2,'0')}}:00</b><span @dblclick="create(format(cursor,'yyyy-MM-dd'))"><article v-for="event in selectedEvents.filter(item=>!item.allDay&&Number(item.time.slice(0,2))===hour-1)" :key="event.id" :style="{borderLeftColor:event.color}" @click="edit(event)"><strong>{{event.time}} · {{event.title}}</strong><small>{{event.endTime?`hasta ${event.endTime} · `:''}}{{event.location||event.calendarId}}</small></article><article v-for="item in selectedMedications.filter(item=>Number(item.time.slice(0,2))===hour-1)" :key="item.id" class="health"><strong>{{item.time}} · {{item.title}}</strong><small>{{item.subtitle}} · Medicación</small></article><article v-for="item in selectedRoutines.filter(item=>Number(item.time.slice(0,2))===hour-1)" :key="item.id" class="routine"><strong>{{item.time}} · {{item.title}}</strong><small>{{item.subtitle}} · Rutina</small></article></span></div></div></template></Card>
<Card v-else class="calendar-surface"><template #content><div v-if="agenda.length" class="agenda-view"><section v-for="date in agendaDates" :key="date"><header><strong>{{formatDate(date,"EEEE d 'de' MMMM")}}</strong><span>{{agenda.filter(item=>item.occurrenceDate===date).length}} eventos</span></header><article v-for="event in agenda.filter(item=>item.occurrenceDate===date)" :key="`${event.id}-${date}`"><span class="agenda-color" :style="{background:event.color}"/><time>{{event.allDay?'Todo el día':event.time}}</time><div><strong :class="{completed:event.completed}">{{event.title}}</strong><small>{{event.calendarId}}<template v-if="event.location"> · {{event.location}}</template></small><p v-if="event.notes">{{event.notes}}</p></div><Tag :value="event.kind==='appointment'?'Turno':event.kind==='task'?'Tarea':'Personal'" severity="secondary" rounded/><Button icon="pi pi-pencil" text rounded @click="edit(event)"/></article></section></div><EmptyState v-else icon="pi pi-calendar" title="No hay eventos próximos" description="Creá un evento para comenzar a organizar tu agenda."/></template></Card></main></div>
<Dialog v-model:visible="visible" modal :header="editingId?'Editar evento':'Nuevo evento'" :style="{width:'min(96vw,52rem)'}"><div class="form-grid"><label class="field full"><span>Título</span><InputText v-model="form.title" placeholder="Ej. Turno odontológico" autofocus/></label><label class="switch-field full"><span><strong>Todo el día</strong><small>Oculta los horarios de inicio y finalización.</small></span><ToggleSwitch v-model="form.allDay"/></label><label class="field"><span>Fecha</span><InputText v-model="form.date" type="date"/></label><label class="field"><span>Calendario</span><Select v-model="form.calendarId" :options="calendars"/></label><label v-if="!form.allDay" class="field"><span>Hora de inicio</span><InputText v-model="form.time" type="time"/></label><label v-if="!form.allDay" class="field"><span>Hora de finalización</span><InputText v-model="form.endTime" type="time"/></label><label class="field"><span>Tipo</span><Select :model-value="form.kind" :options="kinds" option-label="label" option-value="value" @update:model-value="changeKind"/></label><label class="field"><span>Repetición</span><Select v-model="form.recurrence" :options="[{label:'No repetir',value:'none'},{label:'Cada día',value:'daily'},{label:'Cada semana',value:'weekly'},{label:'Cada mes',value:'monthly'},{label:'Cada año',value:'yearly'}]" option-label="label" option-value="value"/></label><label v-if="form.recurrence!=='none'" class="field"><span>Repetir hasta</span><InputText v-model="form.recurrenceUntil" type="date"/></label><label class="field"><span>Ubicación</span><InputText v-model="form.location" placeholder="Dirección o lugar"/></label><label class="field full"><span>Enlace</span><InputText v-model="form.link" placeholder="Google Meet, Zoom o sitio web"/></label><label class="field full"><span>Participantes separados por coma</span><InputText v-model="form.participantsText"/></label><label class="field full"><span>Recordatorios</span><MultiSelect v-model="form.reminderMinutes" :options="reminders" option-label="label" option-value="value" display="chip"/></label><label class="field full"><span>Notas</span><Textarea v-model="form.notes" rows="4" auto-resize/></label><div class="field full"><span>Color</span><div class="color-picker"><button v-for="color in ['#8b5cf6','#0ea5e9','#14b8a6','#f59e0b','#f43f5e','#6366f1']" :key="color" type="button" :style="{background:color}" :class="{selected:form.color===color}" @click="form.color=color"/></div></div></div><template #footer><Button v-if="editingId" label="Eliminar" icon="pi pi-trash" severity="danger" text @click="removeEditing"/><span class="dialog-spacer"/><Button label="Cancelar" severity="secondary" text @click="visible=false"/><Button label="Guardar evento" icon="pi pi-check" @click="save"/></template></Dialog></section></template>
